/** In-app changelog — sync with CHANGELOG.md on GitHub */

export type ChangelogEntry = {
  version: string;
  date: string;
  title: string;
  titleFi?: string;
  highlights: string[];
  highlightsFi?: string[];
  latest?: boolean;
};

export const APP_VERSION = "3.26.1";

export const KSYK_CHANGELOG: ChangelogEntry[] = [
  {
    version: "3.26.1",
    date: "August 2026",
    title: "HOTFIX: blank map reverted. Bigger nav panel on desktop.",
    titleFi: "KIIREKORJAUS: tyhjä kartta korjattu. Isompi reittipaneeli työpöydällä.",
    latest: true,
    highlights: [
      "Hotfix — 3.26.0's aggressive raster fade at high zoom caused a blank-map report on some devices. Reverted to 100% raster opacity at every zoom; the paper-beige ground layer stays as a fallback if tiles ever fail to load. Cleanest of both worlds — you always see either the CARTO basemap or the paper backdrop, never white.",
      "Desktop: NavigationPanel width bumped 24rem → 28rem (sm+) → 32rem (lg+) so the turn-by-turn list has room to breathe and long room names/hallway labels stop wrapping awkwardly.",
    ],
    highlightsFi: [
      "Tyhjän kartan bugin nopea korjaus",
      "Työpöydällä reittipaneeli on nyt isompi",
    ],
  },
  {
    version: "3.26.0",
    date: "August 2026",
    title: "Ground fill (no more white zoom), GeolocateControl removed, wall/room delete + placement ghost, floor 1 default",
    titleFi: "Valkoinen ruutu korjattu, sijainti-nappula pois, seinien ja huoneiden poisto + esikatselu",
    highlights: [
      "Fix: fully-zoomed-in map no longer goes white. Added a MazeMap-adjacent \"paper\" ground fill (dark slate in dark mode) beneath the raster, plus the raster now holds ~35% opacity at zoom 22 instead of fading to 5%.",
      "Removed: the GeolocateControl (\"find me\" real-location button). GPS accuracy on a small indoor campus was rarely useful and the button clashed with the site's navigation UI. Indoor routing still works via the \"Etsi lähtöhuone\" room picker.",
      "Default floor is now 1 on every fresh visit — no more \"the map opens on floor 3 because I last looked there.\" A shared URL with ?floor=2 still wins.",
      "Builder: real-time deletion of rooms + walls. Previously only buildings had a delete path from the property panel; walls (surface=wall on hallways) and rooms now have their own mutations that invalidate the right query so the map updates immediately.",
      "Builder: placement ghost while drawing. Wall/hallway/building/room/measure tools now show a dashed blue preview segment from the last placed waypoint to the cursor, so users see exactly where their next click will land before committing.",
      "Confirmed: dragging building/room corner points already works via SelectionHandles — vertices become circles you can drag; the shape updates live and PATCHes on mouseup.",
    ],
    highlightsFi: [
      "Kartta ei enää muutu valkoiseksi täysin zoomatessa",
      "Poistettu: oikeaa GPS-sijaintia näyttänyt nappula",
      "Oletustaso on aina 1. jaettu linkki voi ohittaa",
      "Rakentaja: seinien ja huoneiden poisto toimii nyt reaaliajassa",
      "Rakentaja: hiiren alla esikatselu piirtotyökaluissa",
    ],
  },
  {
    version: "3.25.9",
    date: "August 2026",
    title: "FL replaced with icon. URL state sync for shareable views.",
    titleFi: "FL-teksti ikoniksi. URL tallentaa kartan tilan jaettaville linkeille.",
    highlights: [
      "The \"FL\" floor label is now a layers icon in both the public map and the builder — belt-and-suspenders against any browser autotranslate that still slips through (Chrome sometimes translates individual elements even with the global translate=\"no\").",
      "MazeMap-style URL sharing: the map now writes `?z=`, `?lat=`, `?lng=`, `?bearing=`, `?pitch=`, `?floor=` to the URL as the user pans/rotates/switches floor. Any copy of that URL restores the exact view — camera + level + rotation. Writes are debounced (300 ms) and use history.replaceState so the back button isn't spammed.",
      "URL params take precedence over the persisted-camera in localStorage, so a shared link always drops the recipient at the intended spot even if they'd panned elsewhere in a previous session.",
    ],
    highlightsFi: [
      "\"FL\" korvattu tasoja-ikonilla — käännösvarma",
      "Karttalinkit tallentavat nyt näkymän — jaettu linkki avaa saman kohdan",
    ],
  },
  {
    version: "3.25.8",
    date: "August 2026",
    title: "Fix: FL→Florida autotranslate. Fix: first-visit bearing. Web search now routes.",
    titleFi: "Korjaus: FL→Florida automaattikäännös. Korjaus: kompassisuunta. Web-haku aloittaa reitityksen.",
    highlights: [
      "Fix — the site now sets translate=\"no\" globally, so Chrome/Safari's auto-translate stops rewriting labels like \"FL\" (floor) to \"Florida\" and garbling room numbers/POI names. The Finnish UI still works via i18n; only browser autotranslate is disabled.",
      "Fix — first-ever visit was booting the map facing north instead of the admin-set bearing. Root cause: /api/map-defaults loads AFTER the map inits, and the re-apply effect deliberately preserved the current bearing. Now: if no persisted camera exists AND the user hasn't rotated yet, applying the admin bearing/pitch when defaults arrive.",
      "Web: clicking a search result now IMMEDIATELY opens the NavigationPanel with the pick as the destination — same MazeMap-style flow the Android app got in 3.25.7. Camera still flies to the room for context; user is then prompted for the origin.",
    ],
    highlightsFi: [
      "Korjaus: FL-lyhenne ei enää käänny \"Florida\"-sanaksi automaattikäännöksissä",
      "Korjaus: ensimmäisellä käynnillä kartta katsoo nyt admin-asetettuun suuntaan",
      "Web: hakutuloksen napautus avaa suoraan reitityksen ja pyytää lähtöpaikkaa",
    ],
  },
  {
    version: "3.25.7",
    date: "August 2026",
    title: "Android: no login, search→destination, 3D toggle. Web: sharper at max zoom.",
    titleFi: "Android: ei kirjautumista, haku→määränpää, 3D. Web: terävämpi kartta.",
    highlights: [
      "Android: no more login gate. The app opens straight to the map like the website. Sign-in moved to Settings as an optional link, only needed for the beacon survey + admin actions.",
      "Android: tapping a search result now IMMEDIATELY sets it as the destination and pops the Lähtöpaikka picker (Oma sijainti / Etsi lähtöhuone). No detour through the room sheet — that's still available by tapping the room on the map.",
      "Android: 3D toggle chip (right-side rail, view-in-AR icon). On → camera tilts to 50°, buildings extrude to floors×3 m with vertical gradient shading and colored tint, rooms extrude as raised slabs sitting on their floor's plate. Off → flat top-down as before.",
      "Web: max-zoom bumped 21→22 so users can inspect individual rooms. Basemap fade past zoom 19 is now aggressive (60% → 15% → 5% at 22) so the blurry overzoomed raster stops fighting the crisp KSYK vector overlay. Raster resampling is explicit linear + slight desaturation at high zoom for a diagram-clean feel.",
    ],
    highlightsFi: [
      "Android: kirjautuminen pois — sovellus avautuu suoraan karttaan",
      "Android: haun tulos → määränpää + Lähtöpaikka-valinta",
      "Android: 3D-nappula — rakennukset ja huoneet kohoavat",
      "Web: terävämpi lähikuva — pohjakartta häivytetään enemmän zoomatessa",
    ],
  },
  {
    version: "3.25.6",
    date: "August 2026",
    title: "Android: full directions flow (Lähtöpaikka). Web: doors + entrances visible in 2D.",
    titleFi: "Android: reittiopastus (Lähtöpaikka). Web: ovet ja sisäänkäynnit näkyviin.",
    highlights: [
      "Android: room sheet gets a big blue \"Suunnista tänne\" button. Tap it → destination locked in, a Lähtöpaikka picker card appears with two quick options: Oma sijainti (uses live GPS puck) or Etsi lähtöhuone (returns you to the search bar in ORIGIN mode with a blue prompt strip).",
      "Android: once both endpoints are set, a bright blue route line is drawn between them with a white casing (visible on any basemap tint). A persistent info chip in the top-left shows distance (m/km), walking time (~1.35 m/s), and both endpoint labels; a small × clears the route.",
      "Android: when the route origin is \"Oma sijainti,\" the route line and info chip update every 3 s as the user walks, so distance/time countdown in real time.",
      "Web: door + entrance markers are now visible in 2D (previously 3D-only). A new circle-chip overlay draws them as unambiguous coloured dots — bright green for entrances, dark grey for interior doors, red for exit-only — with white halos so they read on every basemap.",
      "Web: entrance glow discs boosted (~2× opacity at walking-zoom) so \"you can get in here\" reads from a distance.",
    ],
    highlightsFi: [
      "Android: täydellinen reittiopastus lähtöpaikkavalinnalla",
      "Web: ovet ja sisäänkäynnit näkyvät nyt 2D-tilassa vihreinä pisteinä",
    ],
  },
  {
    version: "3.25.5",
    date: "August 2026",
    title: "Android: on-map search + share-link deep-link + clear offline cache",
    titleFi: "Android: karttahaku, jakolinkit, offline-muistin tyhjennys",
    highlights: [
      "Android: pill-shaped search bar mounted at the top of the map. Filters rooms + buildings as the user types with prefix-scoring (203 → room 203 first, then anything containing 203). Tap a result → floor sets, camera flies, sheet opens.",
      "Android: ksykmaps.fi/?room=<id> now opens the native app directly instead of the browser (App Links intent filter, autoVerify enabled). Cold-start + warm-start supported so the app jumps straight to the room whether it was already running or not.",
      "Android: Settings > Offline data shows the on-disk cache size (\"1.2 MB · buildings, rooms, announcements\") with a Clear button that empties filesDir/api_cache.",
      "Android: about card now reads Version 1.3.0.",
    ],
    highlightsFi: [
      "Android: hakupalkki kartalla — huoneet ja rakennukset",
      "Android: ksykmaps.fi -linkit avaavat sovelluksen",
      "Android: offline-muistin tyhjennys asetuksissa",
    ],
  },
  {
    version: "3.25.4",
    date: "August 2026",
    title: "Android: rooms on the map + room deep-link. Builder: layers toggle.",
    titleFi: "Android: huoneet kartalle. Rakentaja: tasovalikko.",
    highlights: [
      "Android: room polygons now render on top of building shells with colored fills, thin outlines and room-number labels — labels fade in past zoom 18 so distant floors stay uncluttered.",
      "Android: tap a room on the map → bottom sheet with type, capacity, and floor + 'Isolate floor' shortcut. Rooms are hit-tested before buildings, so a tap inside a room selects the room, not the surrounding shell.",
      "Android: 'Open on map' from the Room finder now jumps to the native Map tab, sets the floor, flies the camera to the room and pops the room sheet — instead of opening a browser.",
      "Android: bottom-left pill now shows the floor-filtered room count (\"5 · 42 rooms · Floor 2\") so admins can sanity-check floor filters at a glance.",
      "Builder: LayersToggle popover is now available beside the floor selector, so drafters can preview what the map looks like with buildings/rooms/hallways/labels + POI categories hidden without leaving the builder.",
    ],
    highlightsFi: [
      "Android: huoneet piirtyvät nyt kartalle omilla väreillään",
      "Android: 'Näytä kartalla' avaa natiivin karttavälilehden, ei selainta",
      "Rakentaja: tasovalikko lattian valitsimen vieressä esikatselua varten",
    ],
  },
  {
    version: "3.25.3",
    date: "August 2026",
    title: "Native Android app + MazeMap-style locate/scale on web",
    titleFi: "Natiivi Android-sovellus + MazeMap-tyylinen paikannus",
    highlights: [
      "New: native Android map screen (MapLibre Native) with the same OSM/CARTO Voyager basemap the web uses, KSYK building polygons on top, a floor switcher, and tap-a-building bottom sheet.",
      "New: offline-first API layer on Android — every successful GET is mirrored to disk, and reads fall back to the cached copy when the network can't be reached. First launch needs signal; every subsequent launch opens on the subway.",
      "Map tab is now the Android app's primary destination; the searchable Rooms list stays a step away in the bottom nav.",
      "Web: MapLibre GeolocateControl now ships on the campus map — the blue \"You are here\" puck + heading arrow works on desktop and mobile, matching MazeMap's find-me flow.",
      "Web: metric scale bar in the bottom-left so 5 m vs 50 m is always legible without zooming.",
    ],
    highlightsFi: [
      "Uusi natiivi Android-kartta (MapLibre) samalla tyylillä kuin webissä",
      "Offline-tuki Android-sovellukseen — sovellus avautuu ilman verkkoa",
      "Web-karttaan lisätty \"paikanna minut\" -painike ja mittakaava",
    ],
  },
  {
    version: "3.25.2",
    date: "July 2026",
    title: "Cache-bust redeploy — ship the 3.25.1 builder fix",
    titleFi: "Välimuistin tyhjennys — 3.25.1-korjaus voimaan",
    highlights: [
      "Version bump + forced Vercel rebuild so browsers stop loading the stale pre-3.25.1 bundle. Same code as 3.25.1, new hash — the old builder crash (\"Cannot access 'Mi' before initialization\") is finally gone from every cached client.",
    ],
    highlightsFi: [
      "Uusi julkaisu, joka pakottaa selaimet lataamaan 3.25.1-korjauksen",
    ],
  },
  {
    version: "3.25.1",
    date: "July 2026",
    title: "Fix: builder crash on load (\"Cannot access 'Mi' before initialization\")",
    titleFi: "Korjaus: rakentaja kaatui latauksessa",
    highlights: [
      "Fixed a temporal-dead-zone ReferenceError that crashed the builder immediately after login. Root cause was a useEffect dependency array referencing a callback declared 1500 lines below it — evaluated at render, always fired TDZ.",
      "Refactored the auto-connect nav-nodes event listener to use a ref instead so the effect doesn't have to depend on the callback identifier.",
    ],
    highlightsFi: [
      "Korjaus: rakentaja kaatui latauksessa TDZ-virheeseen",
    ],
  },
  {
    version: "3.25.0",
    date: "July 2026",
    title: "Right-click menu, auto-connect nav nodes, route preview",
    titleFi: "Oikean napin valikko, automaattinen yhdistys, reittiesikatselu",
    highlights: [
      "Right-click any building, room, or nav node for a floating context menu (Properties, Focus, Duplicate, Delete, and — for nodes — Route from/to here).",
      "Auto-connect nearby nav nodes: ⌘K → 'Auto-connect nearby nav nodes (8 m)' links every pair within 8 m on the same floor. Skips duplicates, reports how many edges landed.",
      "Route preview: right-click one node → 'Route from here', right-click another → 'Route to here'. Dijkstra runs over the local graph, animates a fat blue line with white casing, and shows a status chip with the hop count (or 'No path' if the two are disconnected).",
    ],
    highlightsFi: [
      "Oikea klikkaus avaa valikon jokaiselle kohteelle",
      "Automaattinen yhdistys: kaikki 8 m sisällä olevat solmut linkitetään yhdellä komennolla",
      "Reittiesikatselu: valitse aloitus + kohde, Dijkstra piirtää reitin",
    ],
  },
  {
    version: "3.24.0",
    date: "July 2026",
    title: "Figma-style editing: multi-select, ⌘D duplicate, F focus",
    titleFi: "Figma-tyylinen muokkaus: monivalinta, ⌘D-kloonaus, F-tarkennus",
    highlights: [
      "Shift+click to add/remove a building or room from your selection (Figma-standard).",
      "⌘D / Ctrl+D duplicates every selected polygon with a ~5m offset. Each duplicate is undoable via ⌘Z.",
      "F key fits the map to your current selection's combined bounds without changing bearing/pitch.",
      "Selection rendering now honours the multi-selection set so every selected polygon paints with the highlighted stroke + fill.",
      "New shortcuts documented in the ? cheat sheet.",
    ],
    highlightsFi: [
      "Shift+click lisää tai poistaa valinnasta",
      "⌘D kloonaa jokaisen valitun muodon 5 m siirtymällä",
      "F-näppäin sovittaa kartan valinnan ympärille",
    ],
  },
  {
    version: "3.23.0",
    date: "July 2026",
    title: "Camera persistence, nav-graph nodes, SVG import, AO simulation",
    titleFi: "Kameran muisti, navigointigraafi, SVG-tuonti, AO-simulointi",
    highlights: [
      "Bug fix: map no longer resets to north on first login — camera (center, zoom, bearing, pitch) persists to localStorage on every moveend and restores on next visit",
      "Nav graph: new Node + Connect tools in the builder. Click to drop nodes; click two nodes to link them. Persists locally, floor-filtered, blue dots + edges rendered on the map.",
      "SVG import (Figma → KSYK): opens via ⌘K → 'Import SVG floor plan'. Parses every polygon/rect/simple path, drops them into the current viewport center as buildings — drag vertices to refine.",
      "3D AO simulation: hand-authored dark ring polygon around every building base (fill-extrusion-ambient-occlusion isn't in MapLibre 5.x upstream, so we approximate it). Ground shadow tint bumped for more depth.",
      "Entrance glow: green ground disc under each entrance so 'the way in' reads from a distance in 3D.",
      "Light spec switched to anchor='map' so shadows behave world-space (sun stays put as you rotate).",
    ],
    highlightsFi: [
      "Korjaus: kartta ei enää nollaa kääntymistä ensimmäisellä kirjautumisella",
      "Navigointigraafi: Solmu- ja Yhdistä-työkalut rakentajassa",
      "SVG-tuonti Figmasta: ⌘K → 'Import SVG'",
      "3D-tunnelma: AO-rengas jokaisen rakennuksen ympärille",
      "Sisäänkäyntien vihreä hohto 3D:ssä",
    ],
  },
  {
    version: "3.22.0",
    date: "July 2026",
    title: "Round 1 of pro-editor rebuild: ⌘K palette, undo/redo, snap-to-vertex, minimap",
    titleFi: "Ammattilaisen työkalut: ⌘K, kumoa/uudelleen, nappaus, minikartta",
    highlights: [
      "Command palette (⌘K): search-first launcher for every action — switch tool, focus building, toggle 3D, publish, jump to any room by number, and more",
      "Undo / redo: ⌘Z + ⌘⇧Z now work in the builder for every create + delete mutation. Toolbar buttons wired. History stack keeps 50 entries.",
      "Snap-to-vertex: while drawing, cursor within 12px of an existing polygon vertex/endpoint/midpoint snaps + shows an orange crosshair + labelled pill (Vertex / Endpoint / Midpoint) — AutoCAD-standard.",
      "Minimap: bottom-left of the builder shows the whole campus with an orange viewport rectangle. Click to jump. Retina canvas.",
    ],
    highlightsFi: [
      "Komentopaletti (⌘K): kaikki toiminnot yhden pikanäppäimen takana",
      "Kumoa / uudelleen: ⌘Z + ⌘⇧Z toimivat rakentajassa",
      "Nappaus pisteisiin: kohdistin lähellä olemassa olevaa kärkeä lukittuu siihen, oranssi ristinäyttö",
      "Minikartta: koko kampuksen yleiskuva ja katselualue vasemmassa alanurkassa",
    ],
  },
  {
    version: "3.21.0",
    date: "July 2026",
    title: "Floors in builder, no-hyphen room names, nav auto-scroll + reset",
    titleFi: "Kerrokset rakentajassa, ei viivaa huoneiden nimissä, navigaation nollaus",
    highlights: [
      "Builder floor selector — MazeMap-style vertical chip in top-right; rooms filter by active floor, new rooms land on the selected floor",
      "Off-floor rooms fade to 8% opacity as ghost context — you never lose spatial awareness",
      "Room auto-naming drops the hyphen: A1, A2, B12 (was A-1, A-2, B-12)",
      "Navigation: active step auto-scrolls into view + Reset button in the timeline header",
      "Arrival banner (green Flag row) when the user taps the final step",
    ],
    highlightsFi: [
      "Rakentajan kerrosvalitsin, uudet huoneet menevät valittuun kerrokseen",
      "Muiden kerrosten huoneet häivytetään 8% läpinäkyvyyteen",
      "Huoneiden numerointi ilman viivaa: A1, A2, B12",
      "Navigaatio: aktiivinen askel vieritetään näkyviin + Nollaa-nappula",
      "Perilläolobanneri kun käyttäjä pääsee viimeiseen askeleeseen",
    ],
  },
  {
    version: "3.20.0",
    date: "July 2026",
    title: "KSYK Maps rebrand + 3D POI pillars + door/entrance markers",
    titleFi: "KSYK Maps -brändi + 3D-POI-pylväät + ovi/sisäänkäyntimerkit",
    highlights: [
      "Stripped 'by Nordbyte Studio' from browser tab, PWA manifest, splash, header, settings, landing, admin login, and version info",
      "Every generic POI (info, cafe, vending, water, first aid, AED, printer, meeting, parking, bike, restrooms) now extrudes as a 2.2 m colored pillar in 3D",
      "Doors extrude as short gray pads; entrances as taller green pads so users see building access at a glance in 3D",
      "Emergency exits render red",
      "package.json author updated to 'KSYK Maps'",
    ],
    highlightsFi: [
      "Poistettu 'by Nordbyte Studio' otsikoista, manifestista, ja käyttöliittymästä",
      "Jokainen POI näkyy nyt 3D:ssä värillisenä pylväänä",
      "Ovet lyhyinä harmaina alustoina, sisäänkäynnit korkeampina vihreinä",
      "Hätäuloskäynnit punaisia",
    ],
  },
  {
    version: "3.19.0",
    date: "July 2026",
    title: "3D map: sky, sun-lit shading, drop shadows, stair towers, ghost floors",
    titleFi: "3D-kartta: taivas, aurinkovarjostus, varjot, portaikkotornit, aavehuoneet",
    highlights: [
      "MazeMap-style directional light — buildings now cast warm sunlit shading in light mode, cool moonlit in dark mode",
      "Atmospheric sky layer visible when the map is pitched — soft blue horizon with a warm sun halo",
      "Ground drop shadows offset SE under every building for depth",
      "Stair (amber) + elevator (blue) 3D towers pierce the shell so users see where vertical transit lives",
      "Ghost lower floors: rooms below the active floor render at low opacity so the vertical stack always reads",
    ],
    highlightsFi: [
      "MazeMap-tyylinen suunnattu valo — rakennukset lämpimässä auringonvalossa",
      "Ilmakehän taivaskerros kun kartta on kallistettu",
      "Rakennusten varjot kaakkoon syvyyden luomiseksi",
      "Portaikko- (amber) ja hissi- (sininen) 3D-tornit rakennuksen läpi",
      "Alempien kerrosten huoneet läpikuultavina niin pinon rakenne näkyy",
    ],
  },
  {
    version: "3.18.1",
    date: "July 2026",
    title: "Nicer empty states + Publish success flash",
    titleFi: "Paremmat tyhjät tilat + julkaisun onnistumisvinkki",
    highlights: [
      "Search dropdown empty state: iconed hero + 'try a room number' hint",
      "Builder sidebar empty states: colored bubble + wider hint text",
      "Navigation empty state: rich card with directional prompt + how to add endpoints",
      "Publish button flashes green with a checkmark for 2s after a successful publish",
    ],
    highlightsFi: [
      "Hakuvalikko: iso ikoni + 'kokeile huoneen numeroa' -vinkki",
      "Rakentajan sivupalkki: värillinen kuvake + ohje",
      "Navigaatio: rikas ohjekortti kun aloitusta/kohdetta ei ole valittu",
      "Julkaisunappula vihertää + näyttää ✓ kun julkaisu onnistui",
    ],
  },
  {
    version: "3.18.0",
    date: "July 2026",
    title: "Keyboard cheat sheet, ⌘K search, compass pitch dial",
    titleFi: "Pikanäppäinvalikko, ⌘K haku, kompassin kallistus",
    highlights: [
      "Builder: press ? to open a MazeMap-style keyboard cheat sheet (or the floating '?' button)",
      "Header: ⌘K / Ctrl K focuses the search input; keyboard hint pill on the right",
      "Compass chip now shows a thin arc around it that fills with the current 3D pitch",
      "Search input polished: larger, rounded, focus glow, blue search icon while typing",
    ],
    highlightsFi: [
      "Rakentaja: paina ? avataksesi pikanäppäinvalikon",
      "Otsikko: ⌘K / Ctrl K kohdistaa hakukentän",
      "Kompassichip näyttää nyt kallistusmittarin renkaana",
      "Haku suurempi, pyöreämpi, sinisellä ikonin korostuksella",
    ],
  },
  {
    version: "3.17.1",
    date: "July 2026",
    title: "POI category filters, MazeMap coach chip, info sheet hero",
    titleFi: "POI-kategoriasuodattimet, työkaluvinkkichip, tietopaneelin bänneri",
    highlights: [
      "Public map: POI category filters (Transit / Info / Restrooms / Food / Safety / Amenities) in the Layers popover — hide entire groups you don't want",
      "Builder coach chip: icon + tool name + Esc hint + live cursor coords, styled per tool",
      "Feature info sheet: colored hero band matching the entity's tint, bigger title",
    ],
    highlightsFi: [
      "Kartta: POI-kategoriasuodattimet Tasot-valikossa — piilota kokonaisia ryhmiä",
      "Rakentajan ohjenappula: kuvake + työkalun nimi + Esc-vinkki + kohdistin",
      "Tietopaneeli: väriviiva kohteen värillä, isompi otsikko",
    ],
  },
  {
    version: "3.17.0",
    date: "July 2026",
    title: "MazeMap-style POI flyout — toolbar no longer squished",
    titleFi: "MazeMap-tyylinen POI-valikko — työkalupalkki ei enää ahdas",
    highlights: [
      "Builder toolbar refactored into groups: Cursor, Shape, POIs, Delete",
      "All 18 POI tools now live behind a single 'POIs' button that opens a categorised popover (Transit, Info, Restrooms, Food, Safety, Amenities)",
      "Popover tinted per category, matches the map's chip color palette",
      "Group dividers + hotkey ghosts on shape tools for CAD polish",
    ],
    highlightsFi: [
      "Rakentajan työkalupalkki ryhmitelty: Osoitin, Muodot, POI:t, Poisto",
      "18 POI-työkalua nyt yhden POI-napin takana kategoriapopoverissa",
      "Popover värikoodattu kategoreittain, sopii kartan värimaailmaan",
    ],
  },
  {
    version: "3.16.1",
    date: "July 2026",
    title: "Hover highlights, POI tooltip, drag-to-move, active step",
    titleFi: "Osoitinkorostus, POI-vinkki, siirto, aktiivinen askel",
    highlights: [
      "Room + building fill brightens on hover (MazeMap-style feature-state)",
      "Public map POIs show a floating tooltip on hover with kind + floor",
      "Builder: drag anywhere inside a selected building/room to translate the whole shape",
      "Navigation: active step highlighted in the timeline + remaining distance/time pill",
      "Past steps dim so the user's progress is visually obvious",
    ],
    highlightsFi: [
      "Huoneen + rakennuksen täyttö kirkastuu osoitettaessa",
      "Julkinen kartta: POI-vinkki tyyppi + kerros näkyy osoitettaessa",
      "Rakentaja: vedä valitun rakennuksen/huoneen sisältä siirtääksesi koko muotoa",
      "Navigaatio: aktiivinen askel korostettu + jäljellä oleva matka/aika",
      "Menneet askeleet himmenevät niin että edistyminen näkyy visuaalisesti",
    ],
  },
  {
    version: "3.16.0",
    date: "July 2026",
    title: "Configurable 3D heights, CAD polish, HD basemap, 3D toggle fix",
    titleFi: "Säädettävät 3D-korkeudet, CAD-viilaus, HD-taustakartta, 3D-korjaus",
    highlights: [
      "3D toggle fix — first press now shows extrusion (was: only tilted, needed a second press)",
      "Room fill now visible starting at zoom 15 so buildings never hide rooms in public map",
      "Per-building height controls in Style tab: heightPerFloor, totalHeight override, wallThickness",
      "Per-room slab height in Style tab (0.05–2.5 m) for column-style room visuals",
      "CAD: live dimension callouts on every polygon edge (draw + edit), Shift-axis-lock, 15° rotation snap, arrow-key nudge",
      "HD basemap: CARTO Voyager @2x tiles, fade at zoom 19+, room labels + POI chips grow at close zoom",
      "Extended map max zoom from 19 → 21 so users can inspect campus interior detail",
    ],
    highlightsFi: [
      "3D-korjaus — ensimmäinen painallus näyttää nyt rakennukset (ennen: vain kallistus)",
      "Huoneet näkyvät kartalla jo zoomilla 15, eivät piiloudu rakennusten alle",
      "Rakennuskohtaiset korkeussäätimet Style-välilehdellä",
      "Huonekohtainen laatan korkeus Style-välilehdellä",
      "CAD: mittalaput jokaisen polygonin sivulle, Shift-akselilukko, 15° kääntösnap, nuolinäppäinsiirto",
      "HD-taustakartta: CARTO Voyager @2x, hivenettävä zoomilla 19+, huonemerkinnät suuremmiksi",
      "Kartan maksimi zoomia nostettu 19 → 21 sisätilojen tarkasteluun",
    ],
  },
  {
    version: "3.15.0",
    date: "July 2026",
    title: "MazeMap-style 3D + 15 new POIs + turn-by-turn timeline",
    titleFi: "MazeMap-tyylinen 3D + 15 uutta POI:ta + reittiaikajana",
    highlights: [
      "3D scene overhaul: lower walls, floor slabs, roof caps, rooms now stack ON buildings",
      "Three.js walkthrough: hollow building shells, per-floor plates, rooms as raised platforms",
      "Builder POIs: café, vending, water, first aid, AED, printer, meeting point",
      "Navigation: MazeMap-style turn-by-turn timeline with typed icons + floor-change chips",
      "Map: hover cursor on interactive features, floor picker polish",
    ],
    highlightsFi: [
      "3D-uudistus: matalammat seinät, kerroslaatat, katot; huoneet asettuvat rakennuksen päälle",
      "Three.js-kävely: läpinäkyvät rakennuskuoret, kerroslaatat, huoneet kohotettuina alustoina",
      "Rakentajaan POI:t: kahvila, automaatti, vesi, ensiapu, AED, tulostin, tapaamispaikka",
      "Navigaatio: MazeMap-tyylinen käännösohjeaikajana ikoneilla + kerrosvaihtojen merkinnät",
      "Kartta: osoitin muuttuu klikattavien päällä, kerrosvalitsin viimeistelty",
    ],
  },
  {
    version: "3.1.6",
    date: "May 2026",
    title: "2D-only map polish",
    titleFi: "2D-kartan viimeistely",
    highlights: [
      "Removed 2D/3D toggle — home is 2D campus map only for now",
      "Richer map visuals: campus plate, shadows, search results, status legend",
      "Improved builder canvas and room editing panels",
    ],
    highlightsFi: [
      "2D/3D-valitsin poistettu — vain 2D-kartta etusivulla",
      "Kartta: kampusalusta, varjot, haku ja tilalegenda",
      "Rakentajan ulkoasu ja tilamuokkaus parannettu",
    ],
  },
  {
    version: "3.1.5",
    date: "May 2026",
    title: "Aalto Space–style campus map",
    titleFi: "Aalto Space -tyylinen kampuskartta",
    highlights: [
      "2D map: floating search, floor selector, room status colors, layer toggles, bottom sheets",
      "Campus builder: floor-based room editing with Aalto-style controls",
      "3D home view: room blocks per floor on wing footprints",
    ],
    highlightsFi: [
      "2D-kartta: haku, kerrosvalitsin, tilavärit, tasot ja alapaneelit",
      "Rakentaja: kerroskohtaiset tilat Aalto-tyylisillä ohjaimilla",
      "3D-näkymä: tilakuutiot kerroksittain siipien päällä",
    ],
  },
  {
    version: "3.1.4",
    date: "May 2026",
    title: "Official owl logo file & map builders",
    titleFi: "Virallinen pöllölogo ja rakentajat",
    highlights: [
      "App loads ksykmaps_logo_NEW (2).png directly; favicons regenerated from it",
      "2D map wing chips with fly-to-wing zoom and drop shadows",
      "3D view rotates toward selected wing with Finnish labels",
      "Map builder uses campus outline colors and reference labels",
    ],
    highlightsFi: [
      "Sovellus käyttää suoraan ksykmaps_logo_NEW (2).png -tiedostoa",
      "2D-kartta: siipinapit ja zoomaus valittuun siipeen",
      "3D-näkymä kääntyy valitun siiven suuntaan",
      "Karttarakentajan referenssipiirrokset ja värit",
    ],
  },
  {
    version: "3.1.3",
    date: "May 2026",
    title: "New owl logo & map polish",
    titleFi: "Uusi pöllölogo ja karttaselkeys",
    highlights: [
      "New owl map icon across the app, favicons, and PWA manifest",
      "Larger borderless logo on the home screen with soft glow",
      "Wing info cards, touch pan, and pinch-to-zoom on the 2D map",
      "Richer 3D campus view with wing quick-select chips",
      "Premium loader with Finnish and English status messages",
    ],
    highlightsFi: [
      "Uusi pöllö-karttakuvake koko sovelluksessa ja kuvakkeissa",
      "Suurempi reunaton logo etusivulla",
      "Siipitiedot, kosketuspanorointi ja nipistyszoomaus 2D-kartalla",
      "Parannettu 3D-näkymä siipivalitsimilla",
      "Uudistettu latausnäkymä suomeksi ja englanniksi",
    ],
  },
  {
    version: "3.1.2",
    date: "May 2026",
    title: "Campus map refresh",
    titleFi: "Karttapäivitys",
    highlights: [
      "New KSYK Maps logo and sharper icons across the app",
      "Unified top bar with Lunch, HSL, and Settings",
      "Clean wing-outline map (A, U, K, M, R, B) with 2D and 3D views",
      "Redesigned settings with changelog and accessibility options",
      "Improved map builder with undo/redo and pan/zoom",
    ],
    highlightsFi: [
      "Uusi KSYK Maps -logo ja terävämmät kuvakkeet",
      "Yhtenäinen yläpalkki: ruokalista, HSL ja asetukset",
      "Selkeä siipikartta (A, U, K, M, R, B) 2D- ja 3D-näkymillä",
      "Uudistetut asetukset ja muutosloki",
      "Parannettu karttarakentaja",
    ],
  },
  {
    version: "3.1.0",
    date: "March 2026",
    title: "Mobile & admin polish",
    titleFi: "Mobiili ja hallinta",
    highlights: [
      "Enhanced mobile navigation and theme system",
      "Admin settings panel with global theme controls",
      "Announcement banner on home page",
    ],
    highlightsFi: [
      "Parannettu mobiilinavigaatio ja teemat",
      "Hallinta-asetukset",
      "Tiedotebanneri etusivulla",
    ],
  },
  {
    version: "3.0.0",
    date: "2026",
    title: "Nordbyte Studio rebrand",
    titleFi: "Nordbyte Studio -brändäys",
    highlights: [
      "Rebranded to KSYK Maps by Nordbyte Studio",
      "Firebase-backed campus data",
      "Classic and modern map experiences",
    ],
    highlightsFi: [
      "KSYK Maps -brändäys",
      "Firebase-kampusdata",
      "Klassinen ja moderni karttanäkymä",
    ],
  },
];
