/** In-app changelog — sync with CHANGELOG.md on GitHub */

export type ChangelogEntry = {
  version: string;
  date: string;
  title: string;
  titleFi?: string;
  highlights: string[];
  highlightsFi?: string[];
  latest?: boolean;
};

export const APP_VERSION = "3.38.0";

export const KSYK_CHANGELOG: ChangelogEntry[] = [
  {
    version: "3.38.0",
    date: "August 2026",
    title: "Edge-direction ortho, smart guides, corridor property panel, auto nav nodes",
    latest: true,
    highlights: [
      "Ortho now follows the previous edge direction, not just map bearing. After placing two points, every subsequent click snaps to either parallel or perpendicular to the last edge — so any non-axis-aligned building still produces perfect 90° corners.",
      "Smart guides: while drawing, thin orange dashed lines appear when the cursor aligns with any previous waypoint's screen X or Y position — PowerPoint-style alignment hints.",
      "Corridors now have their own property panel (Properties + Style + Transform + Custom tabs, separate from rooms). Selecting a corridor opens the 'Corridor' panel showing label, name, floor, width, and fill opacity.",
      "Creating a corridor auto-places a nav node at its centroid so routing paths connect through it immediately.",
    ],
  },
  {
    version: "3.37.0",
    date: "August 2026",
    title: "Bearing-aware ortho, corridor type fix, corridor fills visible, room fill opacity boost",
    highlights: [
      "Ortho tool is now bearing-aware: axes follow the map's current rotation instead of geographic north. Rotating the map and drawing a room now produces edges aligned with the rotated view.",
      "Ortho auto-close uses the universal rectangle formula D = A + C − B, which works correctly at any bearing (the old formula only worked on north-up maps).",
      "Corridor tool now correctly saves type='hallway' and the corridor's color code to the database. Previously the type was silently dropped, causing newly created corridors to appear in the Rooms list instead of Structure.",
      "Creating a corridor now shows a 'Corridor created' toast and opens the Structure tab automatically.",
      "Corridor fills are visible on the public map — they now use each corridor's stored color (#94a3b8 default) at 0.45 opacity instead of the near-white #e2e8f0 that was invisible on the light basemap.",
      "Room fill opacity in the builder raised from 0.32 → 0.50 so rooms are clearly visible without being selected.",
    ],
    highlightsFi: [
      "Ortho-työkalu seuraa nyt kartan kiertokulmaa, ei maantieteellistä pohjoista.",
      "Käytävätyökalu tallentaa nyt oikean tyyppi- ja värikoodin tietokantaan.",
      "Käytävien täyttöväri näkyy julkisella kartalla — ei enää lähes valkoinen.",
      "Huoneen täytevärin läpinäkyvyys nostettu builderissa.",
    ],
  },
  {
    version: "3.36.0",
    date: "August 2026",
    title: "Corridors in Structure tab, room outlines, POIs visible, rectangle creates rooms, ortho rectangle auto-close",
    highlights: [
      "Clicking a corridor in the builder now opens the Structure tab (not Rooms). Corridor type is stored in GeoJSON feature properties so the click handler can distinguish corridors from rooms.",
      "Room outlines are back on the public map — thin colored borders matching the room fill.",
      "POI markers (stairs, elevators, doors, info, etc.) now appear from zoom 14 instead of 16.",
      "Rectangle tool (X) now creates a room when drawn inside a building footprint. Outside a building it still creates a building. Makes rectangular rooms trivial: one drag.",
      "Ortho 3-point auto-close: pressing Enter with exactly 3 axis-aligned points in room/corridor mode auto-adds the 4th corner for a perfect rectangle.",
      "Wall colors in builder now correctly apply on first load in dark mode (darkMode is now a dep of the hallways layer effect).",
      "Corridors excluded from 3D room extrusions — they were rendering as raised slabs inside 3D buildings.",
    ],
    highlightsFi: [
      "Käytäväalueen klikkaus avaa nyt Structure-välilehden, ei Rooms-välilehteä.",
      "Huoneiden ääriviivat palautettu julkiselle kartalle.",
      "POI-merkit näkyvät zoomitasolta 14 asti.",
      "Suorakulmio-työkalu luo huoneen rakennuksen sisällä tai rakennuksen ulkona.",
      "Ortho-tila sulkee kolmipistemäisen suorakulmion automaattisesti Enter-näppäimellä.",
    ],
  },
  {
    version: "3.35.0",
    date: "August 2026",
    title: "Ortho axis-aligned, corridor separation, POIs tab, wall dark-mode fix, auth fix",
    titleFi: "Ortho suorakulmaiseksi, käytävät erillään, POI-välilehti, seinävärikorjaus, auth-korjaus",
    highlights: [
      "Ortho tool is now truly axis-aligned (horizontal/vertical) — click two points and every subsequent click locks to either the H or V axis from the previous point. Ghost preview matches the committed result.",
      "Corridors (type=hallway) are now separated from rooms in the public map renderer. They render as translucent walkable areas, not as colored room fills, and clicking them no longer opens a room info sheet.",
      "Wall colors are now dark-mode aware. Builder and public map use dark gray (#374151) on light basemap and light slate (#94a3b8) on Dark Matter — updated live via setPaintProperty when the theme toggles.",
      "New POIs tab in the builder sidebar holds stairs, elevators, doors, and all generic service POIs. Structure tab now contains only corridors, hallway paths, and walls.",
      "Owner and editor roles can now create/edit/delete rooms and hallways (previously only admin could — auth guard fixed for all 7 endpoints).",
    ],
    highlightsFi: [
      "Ortho on nyt aidosti vaaka/pystysuuntainen — jokainen klikkaus lukittuu H tai V-akselille edellisestä pisteestä.",
      "Käytävät erottuvat nyt huoneista julkisella kartalla — läpinäkyvät kulkualueet, ei värilliset huonetäytöt.",
      "Seinävärit vaihtuvat tumman tilan mukaan automaattisesti.",
      "Uusi POI-välilehti rakentajassa: portaat, hissit, ovet ja palvelupisteet. Structure-välilehti sisältää vain käytävät, polut ja seinät.",
      "Omistaja- ja muokkaajaroolit voivat nyt luoda/muokata/poistaa huoneita ja käytäviä.",
    ],
  },
  {
    version: "3.33.0",
    date: "August 2026",
    title: "Structure tab, corridors as first-class elements, ortho+snap fix, LayersToggle removed from public map",
    titleFi: "Structure-välilehti, käytävät omana elementtinä, ortho+snap korjaus",
    highlights: [
      "Infra tab renamed to Structure. Corridors (drawn with C) now appear HERE as first-class structural elements — not mixed into the Rooms list. Filter chips grouped: structural (Corridors, Paths, Walls, Stairs, Elevators), access (Doors, Entrances, Exits), then services.",
      "Rooms tab now excludes corridors. The Rooms list shows only actual spaces; corridor-type rooms are managed in the Structure tab with their own property panel access.",
      "Ortho+snap conflict fixed: when Ortho is active after the first edge, vertex-snap no longer hijacks the projection base. Ortho now projects the raw cursor, so the perpendicular constraint is clean. Ghost preview has the same fix.",
      "Corridor ghost preview: the drawn-segment ghost is now slate-grey (#64748b) instead of blue to visually distinguish corridor drawing from room drawing. Ghost was also missing entirely for the corridor tool — fixed.",
      "LayersToggle removed from the public map temporarily. The toggle button is still available in the builder (top-right rail).",
    ],
    highlightsFi: [
      "Infra-välilehti nimetty 'Structure':ksi. Käytävät (C-työkalu) näkyvät täällä, eivät enää Rooms-listassa.",
      "Ortho+snap-konflikti korjattu: ortho käyttää nyt raakaa kursorin sijaintia projektioon.",
      "Käytävän ghost-esikatselu oli puuttunut — korjattu. Käytävä näkyy harmaana, huone sinisenä.",
      "LayersToggle poistettu julkiselta kartalta väliaikaisesti.",
    ],
  },
  {
    version: "3.32.1",
    date: "August 2026",
    title: "Ortho v3 (perpendicular to any edge), Infra tab replaces Layers+POIs",
    titleFi: "Ortho v3 (kohtisuora edelliseen), Infra-välilehti korvaa Layers+POIs",
    latest: false,
    highlights: [
      "Ortho v3 — finally works the way user expected. First edge (2 clicks) is FREE, so you can lay down a wall at any angle. Every subsequent click snaps to the PERPENDICULAR of the previous edge — not axis-aligned. Draw a rectangular corridor at 30° off-north by clicking, dragging in any direction, click, then every subsequent click is locked 90° from the last edge. Ghost preview mirrors the snap.",
      "Deleted Layers tab from LeftSidebar — floor filter + visibility toggles already live in the top-right rail, the sidebar version was a duplicate.",
      "Renamed POIs tab → Infra (Infrastructure). Now clearly holds hallways, walls, corridors, doors, stairs, elevators, entrances, and POI chips — everything that isn't a Building or Room polygon. Prevents \"where do I find walls?\" confusion.",
      "Walls have been in the Infra tab (PoiList) since 3.28.1 with a Walls filter chip — verified rendering path. If they still don't show for you, hit \"Clear all\" in the Nav-graph section then reload — sometimes a stale localStorage entry hides them.",
    ],
    highlightsFi: [
      "Ortho v3: ensimmäinen seinä vapaasti mihin suuntaan tahansa, sen jälkeen jokainen klikkaus kohtisuoraan edelliseen — myös vinoille rakennuksille",
      "Layers-välilehti poistettu, POIs-välilehti nimetty uudelleen \"Infra\":ksi — käytävät, seinät, ovet, portaat, hissit, POI:t yhdessä",
    ],
  },
  {
    version: "3.32.0",
    date: "August 2026",
    title: "Corridor tool (traced polygon hallway), 3D floor-switch nudge, hover-flicker fix",
    titleFi: "Corridor-työkalu (piirrä käytävä huoneena), 3D floor-vaihdon animaatio",
    latest: false,
    highlights: [
      "New Corridor tool (hotkey C) in the builder — trace corridor corners like a Room, Enter to close. Saves as a Room with type=\"hallway\" and a slate-grey color; renders as a filled polygon on both the builder + public map (not just a line). Use it for any walkable area you want to look like a real corridor, not a stroke.",
      "3D mode: floor changes now trigger a small camera pitch-up nudge (+8° for 240ms, back for 260ms) so the level switch reads as a visible transition instead of an instant swap. Only fires when 3D is on; 2D top-down stays instant.",
      "Fix — hover flicker on selected buildings in the builder. Added fill-opacity-transition (120ms) + line-width-transition on the buildings paint so the selected↔unselected paint change eases smoothly instead of snapping. Every feature-collection regeneration used to insta-repaint, which was reading as a flicker on hover.",
      "PoiList: fixed row click on point POIs — now opens PropertyPanel (was just firing fly-to and leaving panel empty).",
      "PoiList: new \"Clear all\" button in Nav-graph header wipes localStorage nav nodes with confirmation. Fixes \"can't delete nav nodes\" — they were in browser storage, not DB.",
    ],
    highlightsFi: [
      "Uusi Corridor-työkalu (pikanäppäin C) — piirrä käytävä huoneen tapaan, saa täytön ja harmaan värin",
      "3D-tila: kerroksen vaihto animoi kameran hieman, jotta muutos näkyy",
      "Korjaus: rakennusten hover-välkkyminen kun ne on valittuna",
    ],
  },
  {
    version: "3.31.3",
    date: "August 2026",
    title: "Ortho v2 (alternating axes), clear-nav-nodes button, POI tab rows select+edit",
    titleFi: "Ortho v2 vuorotellen, navigointinodejen tyhjennys, POI-välilehden rivit avaavat editorin",
    latest: false,
    highlights: [
      "Ortho tool redesigned: consecutive edges now ALTERNATE horizontal ↔ vertical based on the previous edge's orientation (AutoCAD style). Draw a rectangle by clicking, dragging right, click, dragging down, click, dragging left, click, close — every corner is automatically 90°. First segment still picks by cursor's dominant axis.",
      "LeftSidebar POI tab: new \"Clear all\" button in the Nav-graph header explains that nav nodes are per-browser localStorage (not DB) and wipes them in one click. Fixes \"I can't delete nav nodes\" — they weren't stored on the server.",
      "LeftSidebar POI tab rows: clicking a door / stair / elevator / generic POI now OPENS THE PROPERTY PANEL (was just flying the map to the point). Same behavior as clicking the POI on the map, so users can edit floor/kind/delete from either surface.",
    ],
    highlightsFi: [
      "Ortho-työkalu vuorottelee vaaka- ja pystylinjaa (CAD-tyyliin) — täydellinen suorakulmio 4 klikkauksella",
      "Nav-nodet: uusi \"Tyhjennä kaikki\" -nappula sivupaneelissa (nodet ovat vain selaimessa, eivät tietokannassa)",
      "POI-välilehden rivit avaavat nyt muokkauspaneelin",
    ],
  },
  {
    version: "3.31.2",
    date: "August 2026",
    title: "Ortho tool (90° corner snap) + POI paint uses Shape-B resolver",
    titleFi: "Ortho-työkalu (90° kulmalukko) + POI-tyylit tulevat luokkajärjestelmästä",
    latest: false,
    highlights: [
      "New Ortho toggle in the top toolbar (rectangle icon, between Snap and Zoom). When on, every waypoint click while drawing a building / room / rectangle / path / wall snaps to horizontal OR vertical from the previous vertex — locks whichever axis you moved less on. Ghost preview line shows the axis-locked pending segment BEFORE you commit. Perfect right-angle corners without eyeballing.",
      "CampusOverlay POI features now embed their resolved category style (chipColor / strokeColor / icon) as feature properties, fed by @ksyk/shared/poi/categories → resolveCategoryStyle(). Legacy flat kind strings resolve through LEGACY_KIND_MAP to their new category paths. Foundation for admins to register new POI kinds without touching paint code.",
    ],
    highlightsFi: [
      "Ortho-työkalu (90° kulmasnäp) — jokainen klikkaus kohdistuu vaaka- tai pystylinjaan",
      "POI:t saavat tyylinsä luokkajärjestelmästä (Shape B) — perustus admin-CRUD:lle",
    ],
  },
  {
    version: "3.31.1",
    date: "August 2026",
    title: "Path tool renders multi-vertex, walls visible in builder, Wilma schedule link",
    titleFi: "Path-työkalu piirtää monikulmaisia hallytäjä, seinät näkyvät rakentajassa, Wilma-linkki huoneelle",
    latest: false,
    highlights: [
      "Builder: FIXED — the hallway renderer was still using legacy startX/Y → endX/Y for the LineString coordinates, ignoring the multi-vertex points array shipped in 3.30.0. Result: a 4-click L-shape saved correctly but drew as a straight line through walls. Now the builder walks the full points[] polyline (with fallback for older hallways).",
      "Builder: walls (surface=wall on hallways) render as CHUNKY DARK LINES (line-color #1f2937, ~3-12 px width across zoom) instead of the amber walkable-path color. Reads as an obstacle, not a route. Public map already had this.",
      "Room properties: new Schedule link section — Button label + URL. Set a custom label like \"Open in Wilma\" and a URL; a prominent emerald button appears in the room's info drawer that opens the link in a new tab. Falls back to \"Open schedule\" when label is empty.",
      "Type schema: Room gains scheduleUrl + scheduleLabel as first-class optional string columns (with metadata fallback for older rooms).",
    ],
    highlightsFi: [
      "Rakentaja: monikulmaiset hallytäjä piirtyvät nyt kaikilla kulmilla",
      "Rakentaja: seinät näkyvät tummina paksuina viivoina",
      "Huoneelle voi lisätä Wilma-linkin — näkyy vihreänä nappina tietopaneelissa",
    ],
  },
  {
    version: "3.31.0",
    date: "August 2026",
    title: "Shape-B POI category tree, door + entrance pins with tails",
    titleFi: "POI-luokkajärjestelmä (Shape B), ovet + sisäänkäynnit näkyvät pin-muodossa",
    latest: false,
    highlights: [
      "New @ksyk/shared/poi/categories module. Slash-delimited category paths (amenity/food/cafe), per-category displayName/icon/color/searchAliases, nested inheritance via resolveCategoryStyle(), and a legacy alias table so existing kind=\"restroom_m\" resolves to \"amenity/restroom/m\" without a data migration. ~25 categories pre-registered across amenity/info/safety/transit/services. Foundation for a future admin CRUD UI + Firestore-backed registry.",
      "Doors + entrances are now MazeMap-style pins on the public map, matching the POI pin treatment shipped in 3.30.1. Chip translated up so the coordinate sits at the bottom of the pin head; new tail ▼ glyph points to the exact spot. D/E letters translated with the chip so they stay inside the pin head. Entrance chip bumped 5→20 px baseline; door 4→14 px.",
      "Hallway multi-vertex flow verified end-to-end — draw N clicks, Enter finalises, single hallway record with points[] array, CampusOverlay renders full polyline, routing graph adds a waypoint node per vertex.",
    ],
    highlightsFi: [
      "POI-luokkajärjestelmä käyttöön (Shape B) — hierarkkinen kategoriapuu perittävillä tyyleillä",
      "Ovet ja sisäänkäynnit näkyvät nyt tippaan piirrettynä pin-muodossa julkiselle kartalle",
    ],
  },
  {
    version: "3.30.1",
    date: "August 2026",
    title: "MazeMap-style pin POIs, bottom-sheet info drawer on desktop, hallway → Path tool",
    titleFi: "MazeMap-tyyliset kartioviestit, tietopaneeli näytön alalaidasta työpöydällä",
    latest: false,
    highlights: [
      "POI markers are now MazeMap-style pins. The circle chip is translated up so it sits above the coordinate; a small ▼ tail below points to the exact spot. Chunkier baseline (9→24 px radius across zoom 15/19/21) with per-kind tail colour matching the chip's stroke.",
      "Room/building info panel now slides up from the bottom of the screen on desktop too (was floating right-side). Anchored bottom-center, wider on desktop (32/36rem), matches the MazeMap card affordance. Mobile behaviour unchanged.",
      "Builder: renamed the H (Hallway) tool to \"Path\" with coach text \"Click each corner — Enter to finish (N points, min 2)\" so the multi-vertex behaviour is discoverable. Cheat sheet + palette label + coach text all updated.",
    ],
    highlightsFi: [
      "POI:t näkyvät nyt MazeMap-tyylisinä pinneinä (kartiona) — ylempänä koordinaattia, alla pieni häntä osoittamassa tarkkaa kohtaa",
      "Huoneen/rakennuksen tietopaneeli avautuu myös työpöydällä alalaidasta",
      "Rakentaja: \"Hallway\"-työkalu nimetty \"Path\" — vihjaa monikulmaisen tuen",
    ],
  },
  {
    version: "3.30.0",
    date: "August 2026",
    title: "Multi-vertex hallways + routing that actually connects doors↔hallways↔rooms",
    titleFi: "Monikulmaiset käytävät + reititys joka oikeasti yhdistää ovet, käytävät ja huoneet",
    highlights: [
      "Hallways: draw as many vertices as you want. Click 2, 3, 4, N points → Enter finalises a SINGLE polyline hallway (previously we secretly chunked it into N separate 2-point rows in the sidebar). New optional `points: LatLng[]` column on the Hallway schema is the source of truth; legacy startX/Y + endX/Y stay populated as the first/last vertex for backward compat with older readers.",
      "CampusOverlay: hallway renderer uses the full `points` polyline when present, so bent corridors actually bend on the map — no more \"my L-shaped hallway shows as one straight line through a wall.\"",
      "Routing: multi-vertex hallways emit one waypoint node per vertex + edges between every consecutive pair, so Dijkstra can flow through bends.",
      "Routing: DOORS AUTO-WIRE to their neighbours. A door without an explicit connects tuple now gets auto-connected to the nearest room (within ~2 m) AND the nearest hallway waypoint on the same floor (within 5 m) at graph-build time. No more \"I placed a door but the router still can't reach the room\" — the door is the bridge, and the graph builder finds both sides for you.",
    ],
    highlightsFi: [
      "Käytävät voi piirtää usealla kulmalla — yksi käytävä pysyy yhtenä",
      "Reititys: ovet yhdistyvät automaattisesti lähimpään huoneeseen ja käytävään, ei tarvitse käsin määrittää",
    ],
  },
  {
    version: "3.29.0",
    date: "August 2026",
    title: "Photo + hours first-class, bilingual room labels, unisex WC on public map",
    titleFi: "Kuva + aukioloajat huoneen omina kenttinä, kaksikieliset huoneiden nimet",
    highlights: [
      "Room labels on the public map now show BOTH English + Finnish names when both are set (e.g. \"Music Room / Musiikkiluokka\"); when only one is set, it shows alone; the base `name` is dropped from labels per feedback. The room number prefix stays.",
      "Photo URL + Hours are now first-class Room columns (packages/shared types updated). Builder saves them to top-level fields; FeatureInfoSheet reads top-level first with metadata-fallback for older rooms.",
      "Public map (CampusOverlay): new `restroom` POI kind (unisex/generic) picks up the same 🚻 glyph + pink chip color the builder shows. Match with the WC tool added in 3.28.2.",
    ],
    highlightsFi: [
      "Huoneiden nimet näkyvät kaksikielisinä (EN/FI) kartalla",
      "Kuva + aukioloajat ovat nyt huoneen omia kenttiä (ei enää metadatassa)",
      "Julkiselle kartalle unisex WC-piste",
    ],
  },
  {
    version: "3.28.2",
    date: "August 2026",
    title: "Generic POIs editable + resizable, unisex restroom, MazeMap-style emoji icons",
    titleFi: "POI:t muokattavissa + koko säädettävissä, unisex-vessa, MazeMap-tyyliset kuvakkeet",
    highlights: [
      "Builder: generic POIs (info, cafe, water, printer, first-aid, etc.) are now clickable + editable via the same PropertyPanel path as doors/stairs/elevators. Builder fetches /api/pois; PropertyPanel resolver picks it up.",
      "New POI kind: `restroom` (unisex/generic) — placed via the new WC tool in the POI palette. Distinct pink chip; separate from restroom_m (blue ♂), restroom_f (pink ♀), restroom_a (purple ♿).",
      "MazeMap-style POI icons: emoji/symbol glyphs render inside each POI chip on the builder — ☕ cafe, 🚻 restroom, ♂/♀/♿ per-gender restrooms, P parking, 🚲 bike, 🖨 printer, ⚡ defibrillator, ✚ first-aid, ℹ info, ≈ water. Much easier to identify at a glance than colored dots.",
      "POI resize: PointPoiProps gets an Icon size slider (0-30 px). Value 0 uses the default zoom-scaled radius; any positive value pins the circle at that size. Stored in metadata.style.iconSize so the same override works when the map re-renders on data changes.",
      "POI chips also bumped in default size (5→13 px radius across zoom 15/18/20 vs the older 3.5→10) with chunkier white halos so they read more clearly.",
    ],
    highlightsFi: [
      "POI:t muokattavissa: kahvilat, vesipisteet, kirjelaatikot, jne.",
      "Uusi POI-tyyppi: unisex-vessa (WC-työkalu palettissa)",
      "MazeMap-tyyliset kuvakkeet POI-pisteissä (☕ 🚻 ♂ ♀ ♿ P 🚲 🖨 …)",
      "POI-pisteiden koko säädettävissä liukusäätimellä",
    ],
  },
  {
    version: "3.28.1",
    date: "August 2026",
    title: "Doors + stairs + elevators editable in builder, way cleaner announcement dialog",
    titleFi: "Ovet, portaat ja hissit muokattavissa rakentajassa. Siistimpi ilmoitusikkuna.",
    highlights: [
      "Builder: doors, stairs, elevators are now CLICKABLE and EDITABLE. Click any POI chip on the map → the property panel opens with a form: Floor, isEntrance/isExit toggles (doors only), position readout, Save, Delete. Same for stairs and elevators (with a coming-soon note for generic POIs).",
      "PropertyPanel: the new PointPoiProps form appears when a point-POI is selected. The kind pill in the header, the tab strip, and titleFor all know about the new door/stair/elevator/poi kinds.",
      "AnnouncementBanner dialog: MUCH cleaner. Redundant icon tile removed; priority chip + relative time now sit above the title in a tidy row. Title bumped to 2xl/3xl for hierarchy. Divider dropped. Combined with the outline Close button + inline prev/next chevrons from 3.28.0, the modal reads as a focused announcement viewer, not a busy card.",
    ],
    highlightsFi: [
      "Rakentaja: ovet, portaat ja hissit muokattavissa suoraan kartalta",
      "Ilmoitusikkuna paljon siistimpi",
    ],
  },
  {
    version: "3.28.0",
    date: "August 2026",
    title: "POIs visible in builder, EN/FI room names, cleaner announcement dialog, banner reverted",
    titleFi: "POI:t näkyvät rakentajassa, EN/FI-nimet huoneille, siistimpi ilmoitusikkuna",
    highlights: [
      "Builder: POIs (doors, stairs, elevators, generic POIs) are now RENDERED on the builder map. Doors: green E for entrance, X for exit, D for door. Stairs: amber S. Elevators: blue E. Generic POIs colored by category. All filter by the currently-selected floor. Previously invisible in the builder — admins had to publish to see placement.",
      "RoomProps: new Name (English) + Name (Finnish) fields alongside the base Name. Wired to the existing nameEn/nameFi columns in the schema so the search index + future i18n-aware displays pick them up.",
      "AnnouncementBanner: reverted the 3.27.5 size bump per feedback — strip is back to the compact original height. The click-to-open DIALOG is polished instead: wider on desktop (max-w-xl), rounded-3xl, cleaner footer with per/next chevrons + subtle outline Close (was a loud blue CTA).",
      "Building label toggle already exists in the Style tab of the Property panel — check the Show label switch to hide/show a building's name on the map.",
    ],
    highlightsFi: [
      "Rakentaja: ovet, portaat, hissit ja POI:t näkyvät suoraan kartalla",
      "Huoneille englannin- ja suomenkieliset nimikentät",
      "Ilmoituspalkki palautettu — sen sijaan avautuva ikkuna siistimpi",
    ],
  },
  {
    version: "3.27.5",
    date: "August 2026",
    title: "Spawn-on-load, taller header, drag-resize info sheet, better banner. Android v1.8.0: live compass",
    titleFi: "Aloitusnäkymä aina spawnista, isompi yläpalkki, säädettävä tietopaneeli. Android: kompassi.",
    highlights: [
      "Map now ALWAYS opens at the admin-configured spawn (center, zoom, rotation) on fresh page loads. Cross-session persisted camera dropped — every open is a fresh spawn. Shared URLs (?z=&lat=&lng=…) still win so links work.",
      "Map init now waits up to 2 s for /api/map-defaults before painting the first frame, so users no longer briefly see the hardcoded fallback before the real admin spawn arrives.",
      "Search: picking a result now auto-clears the input on all platforms (dispatch/listen for ksyk:search-clear). Dropdown closes immediately, doesn't block the info drawer that opens over the map.",
      "Header: taller on desktop (h-14 mobile / h-16 sm / h-20 lg) so the nav reads as a proper top bar instead of a squished chip.",
      "AnnouncementBanner: taller strip, bigger icon padding, content preview shown on mobile too (was hidden), larger title font at lg+. More scannable.",
      "Info drawer on mobile is DRAG-RESIZABLE — three snap points (peek 35dvh / half 60dvh / full 85dvh). Big drag handle at top; tap cycles sizes, drag up/down snaps to next. Desktop unchanged.",
      "Android v1.8.0 — persistent compass chip appears on the right rail when map bearing is non-zero. Icon spins with the map so \"N\" always points to world-north; tap resets bearing to 0. Camera-move listener means the compass tracks live under your finger.",
    ],
    highlightsFi: [
      "Kartta avautuu aina admin-asettamasta sijainnista",
      "Työpöytäyläpalkki isompi",
      "Ilmoituspalkki näyttää nyt esikatselutekstin myös mobiilissa",
      "Tietopaneelia voi vetää mobiilissa — kolme kokoa",
      "Android: elävä kompassi, joka pyörii kartan mukana",
    ],
  },
  {
    version: "3.27.4",
    date: "August 2026",
    title: "Room clicks widened, info sheet no longer clips top on mobile",
    titleFi: "Huoneiden klikkaus toimii paremmin, tietopaneeli ei enää leikkaudu",
    highlights: [
      "Fix — clicking a room on the map now uses a 6px-radius bbox instead of a point-precise hit-test. Rooms hit rooms-first, then buildings, then hallways, so a tap that overlaps a room inside a building resolves to the room. Much easier to select tiny rooms on touch devices.",
      "Fix — the room/building info drawer no longer clips at the top on mobile. Max-height now leaves 7rem of headroom above (header + search bar), so the entire sheet — photo band, title, metadata, Directions button — is always visible without scrolling off the top. Photo band on mobile is 7rem (was 10rem) so more room for content.",
    ],
    highlightsFi: [
      "Huoneiden klikkaus toimii nyt luotettavammin — myös pieniä huoneita on helpompi valita",
      "Tietopaneeli mahtuu näytölle mobiilissa — ei enää leikkaudu ylälaidasta",
    ],
  },
  {
    version: "3.27.3",
    date: "August 2026",
    title: "Rooms brighter + visible earlier, 3D bearing fixed, search opens info, easy photo/hours editing",
    titleFi: "Huoneet näkyvämmät, 3D-korjaus, hakutulos avaa tietopaneelin, helppo kuva-editointi",
    highlights: [
      "Fix — the 3D toggle no longer resets the map's rotation. Rotation and pitch are now in separate effects, so bumping one preserves the other AND the current center/zoom. Combined with the 3.27.2 fix, the 3D button now truly \"only tilts.\"",
      "Rooms are much more visible now — fill-opacity ramp bumped from 0.35→0.85 to 0.6→0.92 across zoom 15-22. Rooms READ at the \"just zoomed into the campus\" step instead of appearing only when you're already at walking-zoom.",
      "Search results now open the info drawer (with photos + hours + description + Directions button) instead of jumping straight into route mode. Same behaviour as clicking the room on the map. Hit \"Directions here\" in the drawer to route.",
      "Builder → RoomProps: new Info drawer content section. Fields for Photo URL, Hours, and Description save into room.metadata + room.description in one click, so filling in the info drawer no longer requires diving into the Custom-JSON tab. Also added a Floor number field so admins can move a room between floors after creation.",
    ],
    highlightsFi: [
      "Korjaus: 3D nappula ei enää nollaa karttasuuntausta",
      "Huoneet paljon näkyvämmät jo pienemmillä zoomeilla",
      "Hakutulos avaa tietopaneelin (ei mene suoraan reititykseen)",
      "Rakentaja: kuvat, aukioloajat, kuvaukset editoitavissa suoraan huoneen paneelissa",
    ],
  },
  {
    version: "3.27.2",
    date: "August 2026",
    title: "Fix: 3D toggle resetting map. Enriched info sheet with photos + hours.",
    titleFi: "Korjaus: 3D nappula ei enää nollaa karttaa. Tietopaneeli näyttää kuvat + aukioloajat.",
    highlights: [
      "Fix — the 3D toggle no longer resets your pan / zoom back to campus defaults. Root cause: a single \"settings changed\" effect was re-flying center + zoom + bearing + pitch whenever ANY setting changed, so bumping pitchDeg (what the toggle does) accidentally reset everything. Now split into two effects — center/zoom changes preserve current bearing/pitch, and rotation/pitch changes preserve current center/zoom.",
      "FeatureInfoSheet: wider Mappedin-style drawer on desktop (26rem sm+ / 30rem lg+), taller max-height (48rem) so photos + descriptions + hours all fit without scrolling.",
      "FeatureInfoSheet: photo hero. If a room/building's metadata contains `photoUrl` (or `imageUrl` / `image` / `photo`), it's rendered as a 40-vh photo band at the top with a gradient scrim + floating close button. Falls back to the coloured hero when no photo is set.",
      "FeatureInfoSheet: new Contact section — Hours (from metadata.hours), Phone, Email, and Website, all rendered as tap-to-call / tap-to-email / open-in-tab links when present.",
    ],
    highlightsFi: [
      "Korjaus: 3D-nappula ei enää palauta karttaa oletusnäkymään",
      "Tietopaneeli isompi työpöydällä, tukee kuvat + yhteystiedot",
      "Aukioloajat / puhelin / sähköposti / verkkosivu näytetään linkkeinä",
    ],
  },
  {
    version: "3.27.1",
    date: "August 2026",
    title: "Bigger door + entrance chips with letter markers",
    titleFi: "Isommat ovi- ja sisäänkäyntipisteet + kirjaintunnisteet",
    highlights: [
      "Doors on the public map are now ~40% bigger (radius 4→10 px across zoom) with thicker white halos, so they read from further out.",
      "Entrance chips are ~30% bigger (radius 5→14 px) with brighter halos — the primary wayfinding cue now really pops.",
      "Each chip gets a bold white letter inside — \"D\" for door, \"E\" for entrance. Reads clearly even in monochrome / high-contrast modes and helps colorblind users distinguish the two types at a glance.",
    ],
    highlightsFi: [
      "Ovet ja sisäänkäynnit näkyvät nyt isompina ja selkeämpinä pisteinä",
      "Jokaisessa pisteessä D/E-kirjain, jotta tyyppi näkyy heti",
    ],
  },
  {
    version: "3.27.0",
    date: "August 2026",
    title: "Stage room type, marching-ants route, POIs inherit active floor. Android v1.7.0: doors + walls on map.",
    titleFi: "Näyttämö-tyyppi, animoitu reitti. Android: ovet + seinät kartalle.",
    highlights: [
      "New room types recognised: stage (näyttämö), theater/theatre, assembly, chapel, reception — all get distinct auto-colors on both web and Android.",
      "Builder: stairs, elevators, and doors placed with any POI tool now inherit the builder's currently-selected floor (was hardcoded to floor 1). Draw on floor 3 → new stair lands on floor 3.",
      "Web: MazeMap-style \"marching ants\" animation on the active route line. The blue dashes now shift along the line ~6 times/sec so users see the direction of travel from origin to destination. Auto-starts when a route is active, auto-stops when cleared.",
      "Android v1.7.0: doors + entrances now render on the map (green chips for entrances, red for exits, dark grey for interior doors) with white halos so they read clearly on every basemap tint.",
      "Android v1.7.0: walls (hallways with surface=wall) render as dark short line segments. Floor filter applies — only walls on the selected floor show when a floor is isolated.",
    ],
    highlightsFi: [
      "Näyttämö-huonetyyppi lisätty (myös theater, chapel, reception)",
      "POI-työkalut käyttävät valittua kerrosta automaattisesti",
      "Reittiviiva animoituu — kulkusuunta näkyy",
      "Android: ovet, sisäänkäynnit ja seinät piirtyvät kartalle",
    ],
  },
  {
    version: "3.26.8",
    date: "August 2026",
    title: "Extreme tilt/skew for images. Android v1.6.0: category room colors + camera persistence.",
    titleFi: "Voimakkaammat kallistukset kuville. Android v1.6.0: huoneiden autovärit + kameran muisti.",
    highlights: [
      "Image overlay: Tilt range bumped ±60° → ±85° (near-vertical foreshortening) and Skew ±45° → ±80°. Perspective correction of extreme-angle photos is now viable.",
      "Android v1.6.0 — rooms without an explicit colorCode now auto-tint by type (classroom green, lab orange, toilets pink, cafeteria amber, office indigo, gym rose, storage grey, ~20 types). Matches the web CampusOverlay behavior — same room looks the same on both platforms.",
      "Android v1.6.0 — camera persistence. On every camera-idle we save target/zoom/bearing/tilt to SharedPreferences; on next launch we restore the exact view. First-ever launch still auto-fits to the campus bounds; subsequent launches respect your last position and rotation.",
    ],
    highlightsFi: [
      "Kuvien kallistus ja vinouma nyt +-85° / +-80°",
      "Android: huoneet autovärittyvät tyypin mukaan (luokka, labra, wc, ...)",
      "Android: sovellus muistaa viimeisimmän karttanäkymän",
    ],
  },
  {
    version: "3.26.7",
    date: "August 2026",
    title: "Image overlays auto-align to map bearing on import + Align to map button",
    titleFi: "Kuvat suoraan kartan mukaisesti tuotaessa + Kohdista karttaan -nappula",
    highlights: [
      "Import an image while the map is rotated → the image now lands screen-straight instead of world-north-straight. On import we set the overlay's rotation to −map.getBearing() so it visually cancels the map's rotation. Tilt + skew default to 0.",
      "New \"Align to map\" button on the image control panel — one click re-syncs rotation to the current map bearing AND zeros tilt + skew. Fixes the \"rotation shouldn't tilt/pitch\" complaint by giving a fast path back to a clean rectangle aligned with your current view.",
      "\"Reset tilt + skew\" is still there (leaves rotation as-is); the two buttons now share a row so both fixes are equally discoverable.",
    ],
    highlightsFi: [
      "Kuvia tuodessa ne asettuvat suoraan näytön suuntaan",
      "\"Kohdista karttaan\" -nappula palauttaa siistin suorakulmion",
    ],
  },
  {
    version: "3.26.6",
    date: "August 2026",
    title: "Nav panel taller, search em-dash separator, drag-to-move images, tilt reset",
    titleFi: "Reittipaneeli korkeampi, hakuruudun välimerkki –, kuvien raahaus",
    highlights: [
      "NavigationPanel: desktop max-height 70dvh → 85dvh so the turn-by-turn list has real breathing room. Mobile stays gated by the viewport-bottom distance so nothing changes there.",
      "Search results: field separator changed from a middle dot (·) to an em-dash (—). Reads more clearly as \"Building — 105 — Floor 2 — Classroom\" instead of the cramped dot version.",
      "Builder: image overlays are now DRAGGABLE. Click and drag the selected overlay to move it on the map (map's own drag pan is temporarily disabled during a drag so the map doesn't slide out from under it). Touch drag works on tablets. A blue hint chip on the control panel tells you drag is available.",
      "Builder: added \"Reset tilt + skew\" button under the perspective sliders. Zeros both to zero so rotation is pure again without touching the rotation slider.",
    ],
    highlightsFi: [
      "Reittipaneeli mahtuu korkeammaksi työpöydällä",
      "Hakutuloksissa selkeä ajatusviiva erottimena",
      "Kuvia voi nyt raahata suoraan kartalla — myös tabletilla",
      "\"Nollaa kallistus + vinouma\" nappula palauttaa kuvan suoraan",
    ],
  },
  {
    version: "3.26.5",
    date: "August 2026",
    title: "Search clip fix, category room colors, doors snap to walls, image tilt + toolbar",
    titleFi: "Hakuruudun leikkautuminen korjattu, huoneiden autovärit, ovet napsahtavat seiniin",
    highlights: [
      "Fix — the desktop search results dropdown was visually clipping under the top bar for some layouts. Bumped its z-index above the sticky header so it now always sits cleanly on top.",
      "MazeMap-style: rooms with no explicit color now auto-tint based on their type — classroom green, lab orange, toilets pink, cafeteria amber, office indigo, gym rose, storage grey, and more. Explicit colorCode still wins so anything you set in the builder is preserved.",
      "Builder: door + entrance tools now SNAP to the nearest wall within 3 m and use the projected point (not the raw click), so doors always land ON a wall instead of floating inside rooms.",
      "Builder: image overlay gains Tilt (–60° to +60°) and Skew (–45° to +45°) sliders alongside opacity/width/rotation. Tilt narrows the top edge to fake perspective foreshortening; skew shears the top horizontally. Useful for straightening scanned floor plans taken at an angle.",
      "Builder: Import Image button moved into the top toolbar (image icon, next to Import/Export) — a first-class action instead of a floating pill.",
    ],
    highlightsFi: [
      "Työpöytäversion hakukenttä ei enää leikkaudu yläpalkkiin",
      "Huoneet saavat automaattisen värin tyypin mukaan",
      "Ovet napsahtavat lähimpään seinään 3 m sisällä",
      "Kuvan tuontiin lisätty kallistus + vinouma. Nappula siirretty yläpalkkiin.",
    ],
  },
  {
    version: "3.26.4",
    date: "August 2026",
    title: "Builder: reference-image overlay + line preview while drawing",
    titleFi: "Rakentaja: pohjapiirustus-kuvien tuonti ja viivan esikatselu",
    highlights: [
      "Builder: Import a floor plan / architect PDF page / photo and use it as a MazeMap-style tracing layer. Sliders for opacity, width (5–500 m), and rotation (–180° to +180°). \"Recenter\" snaps the image to the current map view; delete button removes it. Overlays persist across reloads in localStorage. Handles multiple images with a collapsible list picker at top-left.",
      "Builder: while drawing a building or room, the segment between corners 1 and 2 now shows as a solid line (previously nothing appeared until you'd placed 3 corners). At 3+ corners the shape closes to a polygon as before. Combined with the dashed cursor-ghost from 3.26.0, you always see exactly what you're placing.",
    ],
    highlightsFi: [
      "Rakentaja: tuo pohjapiirustus-kuva ja käytä sitä pohjana",
      "Rakentaja: piirtäessä kulmat 1-2 näkyvät jo viivana",
    ],
  },
  {
    version: "3.26.3",
    date: "August 2026",
    title: "MazeMap-style hover halos + cache-bust",
    titleFi: "MazeMap-tyylinen hover-korostus + välimuisti tyhjennetty",
    highlights: [
      "Hover the map with your cursor — buildings now get a thick coloured outline (2× normal width, full opacity) so you see exactly which building the cursor is on. Rooms get a bright blue 3–5px halo ring while hovered, matching MazeMap's \"active feature\" affordance.",
      "Cache bump so browsers pick up the previous hotfixes (the blank-map fixes in 3.26.1/3.26.2 might've been masked by stale bundles for some users).",
    ],
    highlightsFi: [
      "Hover-tehoste — kohdistettu rakennus/huone saa kirkkaan reunuksen",
      "Välimuisti tyhjennetty, jotta korjatut versiot latautuvat kaikille",
    ],
  },
  {
    version: "3.26.2",
    date: "August 2026",
    title: "HOTFIX #2: strip style back to minimum + CSS backdrop fallback",
    titleFi: "KIIREKORJAUS #2: tyhjä kartta uudelleen korjattu",
    highlights: [
      "The 3.26.0 background layer was still causing a blank map for some users even after 3.26.1's revert. Removed it entirely — the style now has ONLY the raster layer, matching pre-3.26.0 rendering exactly.",
      "Added a CSS backgroundColor on the map container itself (paper-beige / dark slate). Even if MapLibre fails to init OR the raster tiles fail to load, the map area shows a neutral backdrop, never stark white.",
    ],
    highlightsFi: [
      "Tausta-layer poistettu — sotki karttaa. Container-CSS estää valkoisen ruudun.",
    ],
  },
  {
    version: "3.26.1",
    date: "August 2026",
    title: "HOTFIX: blank map reverted. Bigger nav panel on desktop.",
    titleFi: "KIIREKORJAUS: tyhjä kartta korjattu. Isompi reittipaneeli työpöydällä.",
    highlights: [
      "Hotfix — 3.26.0's aggressive raster fade at high zoom caused a blank-map report on some devices. Reverted to 100% raster opacity at every zoom; the paper-beige ground layer stays as a fallback if tiles ever fail to load. Cleanest of both worlds — you always see either the CARTO basemap or the paper backdrop, never white.",
      "Desktop: NavigationPanel width bumped 24rem → 28rem (sm+) → 32rem (lg+) so the turn-by-turn list has room to breathe and long room names/hallway labels stop wrapping awkwardly.",
    ],
    highlightsFi: [
      "Tyhjän kartan bugin nopea korjaus",
      "Työpöydällä reittipaneeli on nyt isompi",
    ],
  },
  {
    version: "3.26.0",
    date: "August 2026",
    title: "Ground fill (no more white zoom), GeolocateControl removed, wall/room delete + placement ghost, floor 1 default",
    titleFi: "Valkoinen ruutu korjattu, sijainti-nappula pois, seinien ja huoneiden poisto + esikatselu",
    highlights: [
      "Fix: fully-zoomed-in map no longer goes white. Added a MazeMap-adjacent \"paper\" ground fill (dark slate in dark mode) beneath the raster, plus the raster now holds ~35% opacity at zoom 22 instead of fading to 5%.",
      "Removed: the GeolocateControl (\"find me\" real-location button). GPS accuracy on a small indoor campus was rarely useful and the button clashed with the site's navigation UI. Indoor routing still works via the \"Etsi lähtöhuone\" room picker.",
      "Default floor is now 1 on every fresh visit — no more \"the map opens on floor 3 because I last looked there.\" A shared URL with ?floor=2 still wins.",
      "Builder: real-time deletion of rooms + walls. Previously only buildings had a delete path from the property panel; walls (surface=wall on hallways) and rooms now have their own mutations that invalidate the right query so the map updates immediately.",
      "Builder: placement ghost while drawing. Wall/hallway/building/room/measure tools now show a dashed blue preview segment from the last placed waypoint to the cursor, so users see exactly where their next click will land before committing.",
      "Confirmed: dragging building/room corner points already works via SelectionHandles — vertices become circles you can drag; the shape updates live and PATCHes on mouseup.",
    ],
    highlightsFi: [
      "Kartta ei enää muutu valkoiseksi täysin zoomatessa",
      "Poistettu: oikeaa GPS-sijaintia näyttänyt nappula",
      "Oletustaso on aina 1. jaettu linkki voi ohittaa",
      "Rakentaja: seinien ja huoneiden poisto toimii nyt reaaliajassa",
      "Rakentaja: hiiren alla esikatselu piirtotyökaluissa",
    ],
  },
  {
    version: "3.25.9",
    date: "August 2026",
    title: "FL replaced with icon. URL state sync for shareable views.",
    titleFi: "FL-teksti ikoniksi. URL tallentaa kartan tilan jaettaville linkeille.",
    highlights: [
      "The \"FL\" floor label is now a layers icon in both the public map and the builder — belt-and-suspenders against any browser autotranslate that still slips through (Chrome sometimes translates individual elements even with the global translate=\"no\").",
      "MazeMap-style URL sharing: the map now writes `?z=`, `?lat=`, `?lng=`, `?bearing=`, `?pitch=`, `?floor=` to the URL as the user pans/rotates/switches floor. Any copy of that URL restores the exact view — camera + level + rotation. Writes are debounced (300 ms) and use history.replaceState so the back button isn't spammed.",
      "URL params take precedence over the persisted-camera in localStorage, so a shared link always drops the recipient at the intended spot even if they'd panned elsewhere in a previous session.",
    ],
    highlightsFi: [
      "\"FL\" korvattu tasoja-ikonilla — käännösvarma",
      "Karttalinkit tallentavat nyt näkymän — jaettu linkki avaa saman kohdan",
    ],
  },
  {
    version: "3.25.8",
    date: "August 2026",
    title: "Fix: FL→Florida autotranslate. Fix: first-visit bearing. Web search now routes.",
    titleFi: "Korjaus: FL→Florida automaattikäännös. Korjaus: kompassisuunta. Web-haku aloittaa reitityksen.",
    highlights: [
      "Fix — the site now sets translate=\"no\" globally, so Chrome/Safari's auto-translate stops rewriting labels like \"FL\" (floor) to \"Florida\" and garbling room numbers/POI names. The Finnish UI still works via i18n; only browser autotranslate is disabled.",
      "Fix — first-ever visit was booting the map facing north instead of the admin-set bearing. Root cause: /api/map-defaults loads AFTER the map inits, and the re-apply effect deliberately preserved the current bearing. Now: if no persisted camera exists AND the user hasn't rotated yet, applying the admin bearing/pitch when defaults arrive.",
      "Web: clicking a search result now IMMEDIATELY opens the NavigationPanel with the pick as the destination — same MazeMap-style flow the Android app got in 3.25.7. Camera still flies to the room for context; user is then prompted for the origin.",
    ],
    highlightsFi: [
      "Korjaus: FL-lyhenne ei enää käänny \"Florida\"-sanaksi automaattikäännöksissä",
      "Korjaus: ensimmäisellä käynnillä kartta katsoo nyt admin-asetettuun suuntaan",
      "Web: hakutuloksen napautus avaa suoraan reitityksen ja pyytää lähtöpaikkaa",
    ],
  },
  {
    version: "3.25.7",
    date: "August 2026",
    title: "Android: no login, search→destination, 3D toggle. Web: sharper at max zoom.",
    titleFi: "Android: ei kirjautumista, haku→määränpää, 3D. Web: terävämpi kartta.",
    highlights: [
      "Android: no more login gate. The app opens straight to the map like the website. Sign-in moved to Settings as an optional link, only needed for the beacon survey + admin actions.",
      "Android: tapping a search result now IMMEDIATELY sets it as the destination and pops the Lähtöpaikka picker (Oma sijainti / Etsi lähtöhuone). No detour through the room sheet — that's still available by tapping the room on the map.",
      "Android: 3D toggle chip (right-side rail, view-in-AR icon). On → camera tilts to 50°, buildings extrude to floors×3 m with vertical gradient shading and colored tint, rooms extrude as raised slabs sitting on their floor's plate. Off → flat top-down as before.",
      "Web: max-zoom bumped 21→22 so users can inspect individual rooms. Basemap fade past zoom 19 is now aggressive (60% → 15% → 5% at 22) so the blurry overzoomed raster stops fighting the crisp KSYK vector overlay. Raster resampling is explicit linear + slight desaturation at high zoom for a diagram-clean feel.",
    ],
    highlightsFi: [
      "Android: kirjautuminen pois — sovellus avautuu suoraan karttaan",
      "Android: haun tulos → määränpää + Lähtöpaikka-valinta",
      "Android: 3D-nappula — rakennukset ja huoneet kohoavat",
      "Web: terävämpi lähikuva — pohjakartta häivytetään enemmän zoomatessa",
    ],
  },
  {
    version: "3.25.6",
    date: "August 2026",
    title: "Android: full directions flow (Lähtöpaikka). Web: doors + entrances visible in 2D.",
    titleFi: "Android: reittiopastus (Lähtöpaikka). Web: ovet ja sisäänkäynnit näkyviin.",
    highlights: [
      "Android: room sheet gets a big blue \"Suunnista tänne\" button. Tap it → destination locked in, a Lähtöpaikka picker card appears with two quick options: Oma sijainti (uses live GPS puck) or Etsi lähtöhuone (returns you to the search bar in ORIGIN mode with a blue prompt strip).",
      "Android: once both endpoints are set, a bright blue route line is drawn between them with a white casing (visible on any basemap tint). A persistent info chip in the top-left shows distance (m/km), walking time (~1.35 m/s), and both endpoint labels; a small × clears the route.",
      "Android: when the route origin is \"Oma sijainti,\" the route line and info chip update every 3 s as the user walks, so distance/time countdown in real time.",
      "Web: door + entrance markers are now visible in 2D (previously 3D-only). A new circle-chip overlay draws them as unambiguous coloured dots — bright green for entrances, dark grey for interior doors, red for exit-only — with white halos so they read on every basemap.",
      "Web: entrance glow discs boosted (~2× opacity at walking-zoom) so \"you can get in here\" reads from a distance.",
    ],
    highlightsFi: [
      "Android: täydellinen reittiopastus lähtöpaikkavalinnalla",
      "Web: ovet ja sisäänkäynnit näkyvät nyt 2D-tilassa vihreinä pisteinä",
    ],
  },
  {
    version: "3.25.5",
    date: "August 2026",
    title: "Android: on-map search + share-link deep-link + clear offline cache",
    titleFi: "Android: karttahaku, jakolinkit, offline-muistin tyhjennys",
    highlights: [
      "Android: pill-shaped search bar mounted at the top of the map. Filters rooms + buildings as the user types with prefix-scoring (203 → room 203 first, then anything containing 203). Tap a result → floor sets, camera flies, sheet opens.",
      "Android: ksykmaps.fi/?room=<id> now opens the native app directly instead of the browser (App Links intent filter, autoVerify enabled). Cold-start + warm-start supported so the app jumps straight to the room whether it was already running or not.",
      "Android: Settings > Offline data shows the on-disk cache size (\"1.2 MB · buildings, rooms, announcements\") with a Clear button that empties filesDir/api_cache.",
      "Android: about card now reads Version 1.3.0.",
    ],
    highlightsFi: [
      "Android: hakupalkki kartalla — huoneet ja rakennukset",
      "Android: ksykmaps.fi -linkit avaavat sovelluksen",
      "Android: offline-muistin tyhjennys asetuksissa",
    ],
  },
  {
    version: "3.25.4",
    date: "August 2026",
    title: "Android: rooms on the map + room deep-link. Builder: layers toggle.",
    titleFi: "Android: huoneet kartalle. Rakentaja: tasovalikko.",
    highlights: [
      "Android: room polygons now render on top of building shells with colored fills, thin outlines and room-number labels — labels fade in past zoom 18 so distant floors stay uncluttered.",
      "Android: tap a room on the map → bottom sheet with type, capacity, and floor + 'Isolate floor' shortcut. Rooms are hit-tested before buildings, so a tap inside a room selects the room, not the surrounding shell.",
      "Android: 'Open on map' from the Room finder now jumps to the native Map tab, sets the floor, flies the camera to the room and pops the room sheet — instead of opening a browser.",
      "Android: bottom-left pill now shows the floor-filtered room count (\"5 · 42 rooms · Floor 2\") so admins can sanity-check floor filters at a glance.",
      "Builder: LayersToggle popover is now available beside the floor selector, so drafters can preview what the map looks like with buildings/rooms/hallways/labels + POI categories hidden without leaving the builder.",
    ],
    highlightsFi: [
      "Android: huoneet piirtyvät nyt kartalle omilla väreillään",
      "Android: 'Näytä kartalla' avaa natiivin karttavälilehden, ei selainta",
      "Rakentaja: tasovalikko lattian valitsimen vieressä esikatselua varten",
    ],
  },
  {
    version: "3.25.3",
    date: "August 2026",
    title: "Native Android app + MazeMap-style locate/scale on web",
    titleFi: "Natiivi Android-sovellus + MazeMap-tyylinen paikannus",
    highlights: [
      "New: native Android map screen (MapLibre Native) with the same OSM/CARTO Voyager basemap the web uses, KSYK building polygons on top, a floor switcher, and tap-a-building bottom sheet.",
      "New: offline-first API layer on Android — every successful GET is mirrored to disk, and reads fall back to the cached copy when the network can't be reached. First launch needs signal; every subsequent launch opens on the subway.",
      "Map tab is now the Android app's primary destination; the searchable Rooms list stays a step away in the bottom nav.",
      "Web: MapLibre GeolocateControl now ships on the campus map — the blue \"You are here\" puck + heading arrow works on desktop and mobile, matching MazeMap's find-me flow.",
      "Web: metric scale bar in the bottom-left so 5 m vs 50 m is always legible without zooming.",
    ],
    highlightsFi: [
      "Uusi natiivi Android-kartta (MapLibre) samalla tyylillä kuin webissä",
      "Offline-tuki Android-sovellukseen — sovellus avautuu ilman verkkoa",
      "Web-karttaan lisätty \"paikanna minut\" -painike ja mittakaava",
    ],
  },
  {
    version: "3.25.2",
    date: "July 2026",
    title: "Cache-bust redeploy — ship the 3.25.1 builder fix",
    titleFi: "Välimuistin tyhjennys — 3.25.1-korjaus voimaan",
    highlights: [
      "Version bump + forced Vercel rebuild so browsers stop loading the stale pre-3.25.1 bundle. Same code as 3.25.1, new hash — the old builder crash (\"Cannot access 'Mi' before initialization\") is finally gone from every cached client.",
    ],
    highlightsFi: [
      "Uusi julkaisu, joka pakottaa selaimet lataamaan 3.25.1-korjauksen",
    ],
  },
  {
    version: "3.25.1",
    date: "July 2026",
    title: "Fix: builder crash on load (\"Cannot access 'Mi' before initialization\")",
    titleFi: "Korjaus: rakentaja kaatui latauksessa",
    highlights: [
      "Fixed a temporal-dead-zone ReferenceError that crashed the builder immediately after login. Root cause was a useEffect dependency array referencing a callback declared 1500 lines below it — evaluated at render, always fired TDZ.",
      "Refactored the auto-connect nav-nodes event listener to use a ref instead so the effect doesn't have to depend on the callback identifier.",
    ],
    highlightsFi: [
      "Korjaus: rakentaja kaatui latauksessa TDZ-virheeseen",
    ],
  },
  {
    version: "3.25.0",
    date: "July 2026",
    title: "Right-click menu, auto-connect nav nodes, route preview",
    titleFi: "Oikean napin valikko, automaattinen yhdistys, reittiesikatselu",
    highlights: [
      "Right-click any building, room, or nav node for a floating context menu (Properties, Focus, Duplicate, Delete, and — for nodes — Route from/to here).",
      "Auto-connect nearby nav nodes: ⌘K → 'Auto-connect nearby nav nodes (8 m)' links every pair within 8 m on the same floor. Skips duplicates, reports how many edges landed.",
      "Route preview: right-click one node → 'Route from here', right-click another → 'Route to here'. Dijkstra runs over the local graph, animates a fat blue line with white casing, and shows a status chip with the hop count (or 'No path' if the two are disconnected).",
    ],
    highlightsFi: [
      "Oikea klikkaus avaa valikon jokaiselle kohteelle",
      "Automaattinen yhdistys: kaikki 8 m sisällä olevat solmut linkitetään yhdellä komennolla",
      "Reittiesikatselu: valitse aloitus + kohde, Dijkstra piirtää reitin",
    ],
  },
  {
    version: "3.24.0",
    date: "July 2026",
    title: "Figma-style editing: multi-select, ⌘D duplicate, F focus",
    titleFi: "Figma-tyylinen muokkaus: monivalinta, ⌘D-kloonaus, F-tarkennus",
    highlights: [
      "Shift+click to add/remove a building or room from your selection (Figma-standard).",
      "⌘D / Ctrl+D duplicates every selected polygon with a ~5m offset. Each duplicate is undoable via ⌘Z.",
      "F key fits the map to your current selection's combined bounds without changing bearing/pitch.",
      "Selection rendering now honours the multi-selection set so every selected polygon paints with the highlighted stroke + fill.",
      "New shortcuts documented in the ? cheat sheet.",
    ],
    highlightsFi: [
      "Shift+click lisää tai poistaa valinnasta",
      "⌘D kloonaa jokaisen valitun muodon 5 m siirtymällä",
      "F-näppäin sovittaa kartan valinnan ympärille",
    ],
  },
  {
    version: "3.23.0",
    date: "July 2026",
    title: "Camera persistence, nav-graph nodes, SVG import, AO simulation",
    titleFi: "Kameran muisti, navigointigraafi, SVG-tuonti, AO-simulointi",
    highlights: [
      "Bug fix: map no longer resets to north on first login — camera (center, zoom, bearing, pitch) persists to localStorage on every moveend and restores on next visit",
      "Nav graph: new Node + Connect tools in the builder. Click to drop nodes; click two nodes to link them. Persists locally, floor-filtered, blue dots + edges rendered on the map.",
      "SVG import (Figma → KSYK): opens via ⌘K → 'Import SVG floor plan'. Parses every polygon/rect/simple path, drops them into the current viewport center as buildings — drag vertices to refine.",
      "3D AO simulation: hand-authored dark ring polygon around every building base (fill-extrusion-ambient-occlusion isn't in MapLibre 5.x upstream, so we approximate it). Ground shadow tint bumped for more depth.",
      "Entrance glow: green ground disc under each entrance so 'the way in' reads from a distance in 3D.",
      "Light spec switched to anchor='map' so shadows behave world-space (sun stays put as you rotate).",
    ],
    highlightsFi: [
      "Korjaus: kartta ei enää nollaa kääntymistä ensimmäisellä kirjautumisella",
      "Navigointigraafi: Solmu- ja Yhdistä-työkalut rakentajassa",
      "SVG-tuonti Figmasta: ⌘K → 'Import SVG'",
      "3D-tunnelma: AO-rengas jokaisen rakennuksen ympärille",
      "Sisäänkäyntien vihreä hohto 3D:ssä",
    ],
  },
  {
    version: "3.22.0",
    date: "July 2026",
    title: "Round 1 of pro-editor rebuild: ⌘K palette, undo/redo, snap-to-vertex, minimap",
    titleFi: "Ammattilaisen työkalut: ⌘K, kumoa/uudelleen, nappaus, minikartta",
    highlights: [
      "Command palette (⌘K): search-first launcher for every action — switch tool, focus building, toggle 3D, publish, jump to any room by number, and more",
      "Undo / redo: ⌘Z + ⌘⇧Z now work in the builder for every create + delete mutation. Toolbar buttons wired. History stack keeps 50 entries.",
      "Snap-to-vertex: while drawing, cursor within 12px of an existing polygon vertex/endpoint/midpoint snaps + shows an orange crosshair + labelled pill (Vertex / Endpoint / Midpoint) — AutoCAD-standard.",
      "Minimap: bottom-left of the builder shows the whole campus with an orange viewport rectangle. Click to jump. Retina canvas.",
    ],
    highlightsFi: [
      "Komentopaletti (⌘K): kaikki toiminnot yhden pikanäppäimen takana",
      "Kumoa / uudelleen: ⌘Z + ⌘⇧Z toimivat rakentajassa",
      "Nappaus pisteisiin: kohdistin lähellä olemassa olevaa kärkeä lukittuu siihen, oranssi ristinäyttö",
      "Minikartta: koko kampuksen yleiskuva ja katselualue vasemmassa alanurkassa",
    ],
  },
  {
    version: "3.21.0",
    date: "July 2026",
    title: "Floors in builder, no-hyphen room names, nav auto-scroll + reset",
    titleFi: "Kerrokset rakentajassa, ei viivaa huoneiden nimissä, navigaation nollaus",
    highlights: [
      "Builder floor selector — MazeMap-style vertical chip in top-right; rooms filter by active floor, new rooms land on the selected floor",
      "Off-floor rooms fade to 8% opacity as ghost context — you never lose spatial awareness",
      "Room auto-naming drops the hyphen: A1, A2, B12 (was A-1, A-2, B-12)",
      "Navigation: active step auto-scrolls into view + Reset button in the timeline header",
      "Arrival banner (green Flag row) when the user taps the final step",
    ],
    highlightsFi: [
      "Rakentajan kerrosvalitsin, uudet huoneet menevät valittuun kerrokseen",
      "Muiden kerrosten huoneet häivytetään 8% läpinäkyvyyteen",
      "Huoneiden numerointi ilman viivaa: A1, A2, B12",
      "Navigaatio: aktiivinen askel vieritetään näkyviin + Nollaa-nappula",
      "Perilläolobanneri kun käyttäjä pääsee viimeiseen askeleeseen",
    ],
  },
  {
    version: "3.20.0",
    date: "July 2026",
    title: "KSYK Maps rebrand + 3D POI pillars + door/entrance markers",
    titleFi: "KSYK Maps -brändi + 3D-POI-pylväät + ovi/sisäänkäyntimerkit",
    highlights: [
      "Stripped 'by Nordbyte Studio' from browser tab, PWA manifest, splash, header, settings, landing, admin login, and version info",
      "Every generic POI (info, cafe, vending, water, first aid, AED, printer, meeting, parking, bike, restrooms) now extrudes as a 2.2 m colored pillar in 3D",
      "Doors extrude as short gray pads; entrances as taller green pads so users see building access at a glance in 3D",
      "Emergency exits render red",
      "package.json author updated to 'KSYK Maps'",
    ],
    highlightsFi: [
      "Poistettu 'by Nordbyte Studio' otsikoista, manifestista, ja käyttöliittymästä",
      "Jokainen POI näkyy nyt 3D:ssä värillisenä pylväänä",
      "Ovet lyhyinä harmaina alustoina, sisäänkäynnit korkeampina vihreinä",
      "Hätäuloskäynnit punaisia",
    ],
  },
  {
    version: "3.19.0",
    date: "July 2026",
    title: "3D map: sky, sun-lit shading, drop shadows, stair towers, ghost floors",
    titleFi: "3D-kartta: taivas, aurinkovarjostus, varjot, portaikkotornit, aavehuoneet",
    highlights: [
      "MazeMap-style directional light — buildings now cast warm sunlit shading in light mode, cool moonlit in dark mode",
      "Atmospheric sky layer visible when the map is pitched — soft blue horizon with a warm sun halo",
      "Ground drop shadows offset SE under every building for depth",
      "Stair (amber) + elevator (blue) 3D towers pierce the shell so users see where vertical transit lives",
      "Ghost lower floors: rooms below the active floor render at low opacity so the vertical stack always reads",
    ],
    highlightsFi: [
      "MazeMap-tyylinen suunnattu valo — rakennukset lämpimässä auringonvalossa",
      "Ilmakehän taivaskerros kun kartta on kallistettu",
      "Rakennusten varjot kaakkoon syvyyden luomiseksi",
      "Portaikko- (amber) ja hissi- (sininen) 3D-tornit rakennuksen läpi",
      "Alempien kerrosten huoneet läpikuultavina niin pinon rakenne näkyy",
    ],
  },
  {
    version: "3.18.1",
    date: "July 2026",
    title: "Nicer empty states + Publish success flash",
    titleFi: "Paremmat tyhjät tilat + julkaisun onnistumisvinkki",
    highlights: [
      "Search dropdown empty state: iconed hero + 'try a room number' hint",
      "Builder sidebar empty states: colored bubble + wider hint text",
      "Navigation empty state: rich card with directional prompt + how to add endpoints",
      "Publish button flashes green with a checkmark for 2s after a successful publish",
    ],
    highlightsFi: [
      "Hakuvalikko: iso ikoni + 'kokeile huoneen numeroa' -vinkki",
      "Rakentajan sivupalkki: värillinen kuvake + ohje",
      "Navigaatio: rikas ohjekortti kun aloitusta/kohdetta ei ole valittu",
      "Julkaisunappula vihertää + näyttää ✓ kun julkaisu onnistui",
    ],
  },
  {
    version: "3.18.0",
    date: "July 2026",
    title: "Keyboard cheat sheet, ⌘K search, compass pitch dial",
    titleFi: "Pikanäppäinvalikko, ⌘K haku, kompassin kallistus",
    highlights: [
      "Builder: press ? to open a MazeMap-style keyboard cheat sheet (or the floating '?' button)",
      "Header: ⌘K / Ctrl K focuses the search input; keyboard hint pill on the right",
      "Compass chip now shows a thin arc around it that fills with the current 3D pitch",
      "Search input polished: larger, rounded, focus glow, blue search icon while typing",
    ],
    highlightsFi: [
      "Rakentaja: paina ? avataksesi pikanäppäinvalikon",
      "Otsikko: ⌘K / Ctrl K kohdistaa hakukentän",
      "Kompassichip näyttää nyt kallistusmittarin renkaana",
      "Haku suurempi, pyöreämpi, sinisellä ikonin korostuksella",
    ],
  },
  {
    version: "3.17.1",
    date: "July 2026",
    title: "POI category filters, MazeMap coach chip, info sheet hero",
    titleFi: "POI-kategoriasuodattimet, työkaluvinkkichip, tietopaneelin bänneri",
    highlights: [
      "Public map: POI category filters (Transit / Info / Restrooms / Food / Safety / Amenities) in the Layers popover — hide entire groups you don't want",
      "Builder coach chip: icon + tool name + Esc hint + live cursor coords, styled per tool",
      "Feature info sheet: colored hero band matching the entity's tint, bigger title",
    ],
    highlightsFi: [
      "Kartta: POI-kategoriasuodattimet Tasot-valikossa — piilota kokonaisia ryhmiä",
      "Rakentajan ohjenappula: kuvake + työkalun nimi + Esc-vinkki + kohdistin",
      "Tietopaneeli: väriviiva kohteen värillä, isompi otsikko",
    ],
  },
  {
    version: "3.17.0",
    date: "July 2026",
    title: "MazeMap-style POI flyout — toolbar no longer squished",
    titleFi: "MazeMap-tyylinen POI-valikko — työkalupalkki ei enää ahdas",
    highlights: [
      "Builder toolbar refactored into groups: Cursor, Shape, POIs, Delete",
      "All 18 POI tools now live behind a single 'POIs' button that opens a categorised popover (Transit, Info, Restrooms, Food, Safety, Amenities)",
      "Popover tinted per category, matches the map's chip color palette",
      "Group dividers + hotkey ghosts on shape tools for CAD polish",
    ],
    highlightsFi: [
      "Rakentajan työkalupalkki ryhmitelty: Osoitin, Muodot, POI:t, Poisto",
      "18 POI-työkalua nyt yhden POI-napin takana kategoriapopoverissa",
      "Popover värikoodattu kategoreittain, sopii kartan värimaailmaan",
    ],
  },
  {
    version: "3.16.1",
    date: "July 2026",
    title: "Hover highlights, POI tooltip, drag-to-move, active step",
    titleFi: "Osoitinkorostus, POI-vinkki, siirto, aktiivinen askel",
    highlights: [
      "Room + building fill brightens on hover (MazeMap-style feature-state)",
      "Public map POIs show a floating tooltip on hover with kind + floor",
      "Builder: drag anywhere inside a selected building/room to translate the whole shape",
      "Navigation: active step highlighted in the timeline + remaining distance/time pill",
      "Past steps dim so the user's progress is visually obvious",
    ],
    highlightsFi: [
      "Huoneen + rakennuksen täyttö kirkastuu osoitettaessa",
      "Julkinen kartta: POI-vinkki tyyppi + kerros näkyy osoitettaessa",
      "Rakentaja: vedä valitun rakennuksen/huoneen sisältä siirtääksesi koko muotoa",
      "Navigaatio: aktiivinen askel korostettu + jäljellä oleva matka/aika",
      "Menneet askeleet himmenevät niin että edistyminen näkyy visuaalisesti",
    ],
  },
  {
    version: "3.16.0",
    date: "July 2026",
    title: "Configurable 3D heights, CAD polish, HD basemap, 3D toggle fix",
    titleFi: "Säädettävät 3D-korkeudet, CAD-viilaus, HD-taustakartta, 3D-korjaus",
    highlights: [
      "3D toggle fix — first press now shows extrusion (was: only tilted, needed a second press)",
      "Room fill now visible starting at zoom 15 so buildings never hide rooms in public map",
      "Per-building height controls in Style tab: heightPerFloor, totalHeight override, wallThickness",
      "Per-room slab height in Style tab (0.05–2.5 m) for column-style room visuals",
      "CAD: live dimension callouts on every polygon edge (draw + edit), Shift-axis-lock, 15° rotation snap, arrow-key nudge",
      "HD basemap: CARTO Voyager @2x tiles, fade at zoom 19+, room labels + POI chips grow at close zoom",
      "Extended map max zoom from 19 → 21 so users can inspect campus interior detail",
    ],
    highlightsFi: [
      "3D-korjaus — ensimmäinen painallus näyttää nyt rakennukset (ennen: vain kallistus)",
      "Huoneet näkyvät kartalla jo zoomilla 15, eivät piiloudu rakennusten alle",
      "Rakennuskohtaiset korkeussäätimet Style-välilehdellä",
      "Huonekohtainen laatan korkeus Style-välilehdellä",
      "CAD: mittalaput jokaisen polygonin sivulle, Shift-akselilukko, 15° kääntösnap, nuolinäppäinsiirto",
      "HD-taustakartta: CARTO Voyager @2x, hivenettävä zoomilla 19+, huonemerkinnät suuremmiksi",
      "Kartan maksimi zoomia nostettu 19 → 21 sisätilojen tarkasteluun",
    ],
  },
  {
    version: "3.15.0",
    date: "July 2026",
    title: "MazeMap-style 3D + 15 new POIs + turn-by-turn timeline",
    titleFi: "MazeMap-tyylinen 3D + 15 uutta POI:ta + reittiaikajana",
    highlights: [
      "3D scene overhaul: lower walls, floor slabs, roof caps, rooms now stack ON buildings",
      "Three.js walkthrough: hollow building shells, per-floor plates, rooms as raised platforms",
      "Builder POIs: café, vending, water, first aid, AED, printer, meeting point",
      "Navigation: MazeMap-style turn-by-turn timeline with typed icons + floor-change chips",
      "Map: hover cursor on interactive features, floor picker polish",
    ],
    highlightsFi: [
      "3D-uudistus: matalammat seinät, kerroslaatat, katot; huoneet asettuvat rakennuksen päälle",
      "Three.js-kävely: läpinäkyvät rakennuskuoret, kerroslaatat, huoneet kohotettuina alustoina",
      "Rakentajaan POI:t: kahvila, automaatti, vesi, ensiapu, AED, tulostin, tapaamispaikka",
      "Navigaatio: MazeMap-tyylinen käännösohjeaikajana ikoneilla + kerrosvaihtojen merkinnät",
      "Kartta: osoitin muuttuu klikattavien päällä, kerrosvalitsin viimeistelty",
    ],
  },
  {
    version: "3.1.6",
    date: "May 2026",
    title: "2D-only map polish",
    titleFi: "2D-kartan viimeistely",
    highlights: [
      "Removed 2D/3D toggle — home is 2D campus map only for now",
      "Richer map visuals: campus plate, shadows, search results, status legend",
      "Improved builder canvas and room editing panels",
    ],
    highlightsFi: [
      "2D/3D-valitsin poistettu — vain 2D-kartta etusivulla",
      "Kartta: kampusalusta, varjot, haku ja tilalegenda",
      "Rakentajan ulkoasu ja tilamuokkaus parannettu",
    ],
  },
  {
    version: "3.1.5",
    date: "May 2026",
    title: "Aalto Space–style campus map",
    titleFi: "Aalto Space -tyylinen kampuskartta",
    highlights: [
      "2D map: floating search, floor selector, room status colors, layer toggles, bottom sheets",
      "Campus builder: floor-based room editing with Aalto-style controls",
      "3D home view: room blocks per floor on wing footprints",
    ],
    highlightsFi: [
      "2D-kartta: haku, kerrosvalitsin, tilavärit, tasot ja alapaneelit",
      "Rakentaja: kerroskohtaiset tilat Aalto-tyylisillä ohjaimilla",
      "3D-näkymä: tilakuutiot kerroksittain siipien päällä",
    ],
  },
  {
    version: "3.1.4",
    date: "May 2026",
    title: "Official owl logo file & map builders",
    titleFi: "Virallinen pöllölogo ja rakentajat",
    highlights: [
      "App loads ksykmaps_logo_NEW (2).png directly; favicons regenerated from it",
      "2D map wing chips with fly-to-wing zoom and drop shadows",
      "3D view rotates toward selected wing with Finnish labels",
      "Map builder uses campus outline colors and reference labels",
    ],
    highlightsFi: [
      "Sovellus käyttää suoraan ksykmaps_logo_NEW (2).png -tiedostoa",
      "2D-kartta: siipinapit ja zoomaus valittuun siipeen",
      "3D-näkymä kääntyy valitun siiven suuntaan",
      "Karttarakentajan referenssipiirrokset ja värit",
    ],
  },
  {
    version: "3.1.3",
    date: "May 2026",
    title: "New owl logo & map polish",
    titleFi: "Uusi pöllölogo ja karttaselkeys",
    highlights: [
      "New owl map icon across the app, favicons, and PWA manifest",
      "Larger borderless logo on the home screen with soft glow",
      "Wing info cards, touch pan, and pinch-to-zoom on the 2D map",
      "Richer 3D campus view with wing quick-select chips",
      "Premium loader with Finnish and English status messages",
    ],
    highlightsFi: [
      "Uusi pöllö-karttakuvake koko sovelluksessa ja kuvakkeissa",
      "Suurempi reunaton logo etusivulla",
      "Siipitiedot, kosketuspanorointi ja nipistyszoomaus 2D-kartalla",
      "Parannettu 3D-näkymä siipivalitsimilla",
      "Uudistettu latausnäkymä suomeksi ja englanniksi",
    ],
  },
  {
    version: "3.1.2",
    date: "May 2026",
    title: "Campus map refresh",
    titleFi: "Karttapäivitys",
    highlights: [
      "New KSYK Maps logo and sharper icons across the app",
      "Unified top bar with Lunch, HSL, and Settings",
      "Clean wing-outline map (A, U, K, M, R, B) with 2D and 3D views",
      "Redesigned settings with changelog and accessibility options",
      "Improved map builder with undo/redo and pan/zoom",
    ],
    highlightsFi: [
      "Uusi KSYK Maps -logo ja terävämmät kuvakkeet",
      "Yhtenäinen yläpalkki: ruokalista, HSL ja asetukset",
      "Selkeä siipikartta (A, U, K, M, R, B) 2D- ja 3D-näkymillä",
      "Uudistetut asetukset ja muutosloki",
      "Parannettu karttarakentaja",
    ],
  },
  {
    version: "3.1.0",
    date: "March 2026",
    title: "Mobile & admin polish",
    titleFi: "Mobiili ja hallinta",
    highlights: [
      "Enhanced mobile navigation and theme system",
      "Admin settings panel with global theme controls",
      "Announcement banner on home page",
    ],
    highlightsFi: [
      "Parannettu mobiilinavigaatio ja teemat",
      "Hallinta-asetukset",
      "Tiedotebanneri etusivulla",
    ],
  },
  {
    version: "3.0.0",
    date: "2026",
    title: "Nordbyte Studio rebrand",
    titleFi: "Nordbyte Studio -brändäys",
    highlights: [
      "Rebranded to KSYK Maps by Nordbyte Studio",
      "Firebase-backed campus data",
      "Classic and modern map experiences",
    ],
    highlightsFi: [
      "KSYK Maps -brändäys",
      "Firebase-kampusdata",
      "Klassinen ja moderni karttanäkymä",
    ],
  },
];
